[레벨 1 글쓰기 미션] 폴라(장유진) 미션 제출합니다.
woowacourse/woowa-writing pull request #122
Opened 2024-03-28 12:48 UTC by jinchiim

휴 첫 줄을 작성하는게 정말 어렵네요 🥲
기술 글을 쓰는 것보다 더 어려웠던 것 같습니다 ㅋㅋㅋㅋ
최대한 담백하게 담아보려고 했는데 잘 느껴지려나 모르겠네요! 

새로운 분들도 많이 뵙는데, 폴라라고 하고 잘 부탁드립니다! 👋🏻

2024-03-29 12:30 UTC, hyeon0208 commented
폴라

2024-03-29 13:33 UTC, donghoony reviewed
1번 페어 폴라 최고 😁

개발자로서 쉬는 것은 정말 가져야 할 덕목(?)이라고 생각합니다. 롱런해야죠!

읽으면서 어색한 부분을 코멘트합니다, 확인해주세요~

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +그래서 그랬을까 내가 좋아하는 분야에서 만큼은 노력이 뒤처지지 않았으면 했다.<br>
- 앞쪽 문장에 쉼표로 독자에게 숨을 고를 시간을 주면 자연스레 뒤쪽이 읽힐 수 있겠네요!
- '-에서만큼'은 붙여 씁니다. ([참고](https://twitter.com/urimal365/status/496507310294827008))
```suggestion
그래서 그랬을까, 내가 좋아하는 분야에서만큼은 노력이 뒤처지지 않았으면 했다.<br>
```

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +성공에는 운이 80퍼센트라는 이야기가 있다. 그리고 나는 그 80퍼센트가 없는 사람이었다.<br>
(개인적인 의견) 글 첫머리니, 감정을 조금 담으면 풍부해지면서 호기심을 자극할 수 있겠죠? (더 알맞은 단어가 있을지도 몰라요!)
```suggestion
성공에는 운이 80퍼센트라는 이야기가 있다. 애석하게도 나는 80퍼센트가 없는 사람이었다.<br>
```

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +그리고 그 덕분에 성과를 이뤘을 때는, 노력만으로 모든 게 될 것이라고 굳게 믿기도 했다.
불필요한 조사를 지워서 매끄럽게 만들어 볼까요? 문장은 단호하게 마무리!
```suggestion
끝내 성과를 이뤘을 때, 모든 것은 노력만으로 해낼 수 있다고 굳게 믿었다.
```

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +황새가 되려면 무얼 해야 하는지도 모르면서 막연히 "열심히"만 한 게 후회됐다. <br>
아랫 문단에서의 강조는 작은 따옴표를 썼네요. 통일해 볼까요? 일반적으로 자신의 생각을 표현하거나, 단어를 강조할 때에는 작은 따옴표를 사용합니다 🙂

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +백엔드 개발자가 되기 위한 목표를 세웠고, 그 자리에 우아한 테크 코스가 있었다.
고유명사 `우아한테크코스`는 붙여 씁니다!

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +거기에 함께하는 조마저 성격이 잘 맞아 가끔 운이 좋다고 생각했다.
가끔 운이 좋은 건 뭐죠???? 뭐죠????? 😡

2024-03-29 13:33 UTC, donghoony commented on level1.md
> +이러다가는 완주도 하지 못하고 점점 앞서나가는 다른 크루들을 보며, 불안함에 떨었던 시간을 후회할 것 같았다.
앞서나가는 다른 크루들이 완주를 하지 못한다고 해석될 여지가 있습니다. 문장을 나눠 볼까요?

2024-04-01 05:26 UTC, healim01 reviewed
안녕하세요 폴라! FE 크루 헤일리입니다. 🍀

폴라의 글 잘 읽었습니다! 
저도 노력해도 일이 잘 안풀릴 때는 노력이 사람을 배신하나라고 생각이 드는거 같아요. 하지만 돌아보면 그 노력 덕분에 얻은게 어딘간 있지 않을까요? 하물며 스스로의 상태를 파악할 수 있었던 도구라고도 생각해볼 수 있을거 같아요. 

현재 폴라는 벌써 원하는 목표도 설정하시고 이를 이루기 위해 계획까지 세우신걸 보면 곧 이 목표도 성취하실 수 있지 않을까 싶네요! 우리 같이 10개월짜리 마라톤을 달려봅시다!! 😆
미션 수행하시느라 수고 많으셨어요!

2024-04-01 05:26 UTC, healim01 commented on level1.md
> +쉬는 것도 하나의 계획으로 둔 셈이다.<br>
쉬는 걸 계획으로 두다니 정말 좋은거 같아요! 
저도 최대한 퇴근 이후에는 우테코 말고 다른 취미 활동이나 운동을 하면서 휴식을 하려고 노력해요. 어쩔때는 칼퇴를 하기 위해서 크루들과 열심히 달리고 칼퇴해서 집에서 쉴 때 얼마나 좋은지 모르겠어요. 

레이싱 자동차들도 레이싱 도중에 잠깐 멈춰서 자동차를 정비하는 시간을 갖는 것처럼 사람도 더 많이 달려나가려면 지금 잠깐은 쉬는 것처럼 보일 수 있어도 이게 다 미래를 위한 정비를 하는 시간이 아닐까요?

2024-04-01 05:26 UTC, healim01 commented on level1.md
> +언젠가 쉬는 것도, 개발도 잘하는 크루가 될 수 있기를 빌어보겠다.
아직 레벨 1인데 계획도 모두 짜시고, 목표까지 있으시다니! 
시작이 반이라는 말이 있는 이정도면 80%는 헤치운게 아닐까요? 하하 
폴라가 `언젠가 쉬는 것도, 개발도 잘하는 크루`가 될 수 있도록 응원하겠습니다!

2024-04-01 05:33 UTC, Hogu59 commented
폴라 안녕하세요,
안드로이드 6기 크루 악어 🐊 입니다!

폴라의 글을 보면서 많이 공감이 되네요.
다른 잘하는 크루들을 보면서 느끼는 감정들.. 저 역시도 똑같이 느끼고 있어, 마치 제 이야기를 보는듯 했습니다.

하지만 결국 마라톤인만큼 완주가 우리의 목표가 되면 좋을것 같습니다.
우리가 중간 중간 불안해하고 좌절해하는 이유는, 아마도 `적어도 상위권(혹은 상위권이라고 불릴만한 수준)에 내가 들어가야해!` 가 문득 목표가 되어 그런 것은 아닐까 싶습니다.
적어도 저는 그런 것 같거든요... 😅 

10개월의 기간동안 찰나의 순간에서 의미있는 (혹은 의미를 두었던) 학습을 쌓아나간다면, 지금 생각하고 있는 폴라의 꿈에 조금 더 가까워질 수 있을 것 같습니다.

수정에 대한 피드백은 다른 크루분들께서 잘 남겨주셔서 저는 글 전체에 대한 평만 남기도록 하겠습니다!

레벨2에서도 쉬는 것도, 개발도 잘하는 폴라가 되길 기대합니다. 😄 💪

2024-04-01 06:05 UTC, kelly6bf approved these changes

2024-04-01 06:05 UTC, kelly6bf commented on level1.md
> +누군가 2시간을 투자하면 나는 4시간을 하고, 누군가 4시간을 투자하면 나는 8시간을 했다.
말은 누구나 쉽게 할 수 있지만, 실행은 아무나 할 수 없는 아주 어려운걸 폴라는 해내고 있었던거에요. 이거야 말로 그 누구도 쉽게 가지지 못하는 폴라의 재능입니다.

2024-04-01 06:05 UTC, kelly6bf commented on level1.md
> +황새가 되고 싶어 발버둥 쳤지만,  <br>
`황새`가 그저 폴라에게 어울리지 않았을 뿐이라고 생각해요. 정말 뻔한 말이지만 오히려 폴라는 `백조`에 어울리는 사람이에요. 이미 눈치챘겠지만 폴라만이 가진 노력하는 재능에 가장 어울리는 새니까요.

폴라는 실패하지 않았고 그 무엇도 망가지지 않았어요. 그냥 아주 잠깐 잘못된 길로 들어선거 뿐이에요.

2024-04-01 06:07 UTC, kelly6bf commented
원래 대부분의 사람들은 스스로의 가치를 눈치채지 못하고 과소평가 한다고 해요. 만약 스스로의 가치를 높이 평가하는 사람이 있으면 오히려 그 사람이 `나르시스트`일 가능성이 높죠.

폴라가 스스로의 가치를 알아보지 못해도 이미 폴라의 노력, 열정, 실력을 알아줄 동료들이 여기에 많이 있어요. 지금 당장은 스스로를 인정하기 힘들 수 있으니 제가 직접 전할게요.

폴라는 그 누구에게도 뒤쳐지지 않을 만큼 노력하고 있고 잘 달려오고 있어요. 너무 잘 하고 있어요.

2024-04-02 04:40 UTC, zangsu requested changes
브리조 야망꾼 폴라, 이야기 재미있게 잘 읽었습니다! 👍 
몇 가지 제안사항 남겨두었으니 참고 부탁드려요!!

2024-04-02 04:40 UTC, zangsu commented on level1.md
> +성공에는 운이 80퍼센트라는 이야기가 있다. 그리고 나는 그 80퍼센트가 없는 사람이었다.<br>
```suggestion
성공에는 운이 80퍼센트라는 이야기가 있다. 나는 20퍼센트 짜리 사람이었다.<br>
```
폴라는 운이 없다는 것을 강조하고 싶었던 것 같아요. 그렇다면 수치적으로도 더 적은 숫자를 사용해 보는 것도 느낌을 달리 할 수 있을지도 모르겠네요!

2024-04-02 04:40 UTC, zangsu commented on level1.md
> +결국 그렇게 믿었던 노력으로 인해서 모든 게 망가지고 나서야 스스로가 뱁새였다는 것을 알았다. <br>
```suggestion
노력으로 인해서 모든 게 망가지고 나서야 스스로가 뱁새였다는 것을 알았다. <br>
```
노력을 믿었다는 것을 강조하고 싶다면 충분히 지금도 자연스럽지만, 노력을 믿었다는 사실이 이미 위에서 나타나는 만큼 생략을 해 주는 것도 좋을 것 같아요.

2024-04-02 04:40 UTC, zangsu commented on level1.md
> +열심히 하라고만 했지, 왜 그 누구도 열심히만 한다고 성공할 수 있는 게 아니라는 말은 해주지 않았을까?
모든 열심히 하는 사람이 성공할 수 있는 건 아니란 사실은 어떤 이에겐 참 아픈 말인 것 같아요. 열심히 하는 모두가 노력의 열매를 맺을 수 있다면 얼마나 좋을까요 😢

2024-04-02 04:40 UTC, zangsu commented on level1.md
> +목표에 한해서는 작은 것부터, 멀게는 3년 뒤의 미래까지 계획을 세웠다. <br>
J 세요?

2024-04-02 04:40 UTC, zangsu commented on level1.md
> +그리고 2023년 4월, 처음으로 코드를 쳤을 때 나는 평생 이 일을 하겠구나 싶었다.
코딩을 처음 시작했던 순간이 폴라에겐 정말 강렬한 기억이 된 것 같아요. 조금 더 자세한 상황이 궁금해 지는군요 🤔

2024-04-02 04:52 UTC, HoeSeong123 reviewed
좋은 글 잘 읽었습니다.

열정적인 사람인 것 같다고 생각은 했는데 글을 읽어보니 제가 생각한 것보다 더 열정 있는 사람이었네요 폴라
폴라 같은 사람들 덕분에 저같이 게으른 사람도 우테코만 오면 열정적으로 변하게 되는 것 같습니다.

10개월 동안 지치지 말고 끝까지 함께 달려갔으면 좋겠습니다😄

2024-04-02 05:58 UTC, jinchiim commented on level1.md
> +결국 그렇게 믿었던 노력으로 인해서 모든 게 망가지고 나서야 스스로가 뱁새였다는 것을 알았다. <br>
그쵸 다리 길어 봤자 뭐하나요. 뱁새가 더 귀여운데.

2024-04-02 09:16 UTC, Hogu59 approved these changes

2024-04-03 02:08 UTC, hyeon0208 approved these changes

2024-04-03 02:26 UTC, healim01 approved these changes

2024-04-03 05:05 UTC, kelly6bf approved these changes

2024-04-03 05:49 UTC, zangsu approved these changes
폴라는 운이 없는 사람이 아니라 정말 꼭 필요한 순간에 운이 발현되는 순간이라고 믿어보는 건 어떨까요?
지금까지 운이 없었던 건, 미래를 위해 저축을 해 두었기 때문이라고 생각해요.

글쓰기 미션 고생하셨습니다!

2024-04-03 05:49 UTC, zangsu commented on level1.md
> +거기에 함께하는 조마저 성격이 잘 맞아 매일 운이 좋다고 생각했다.
👍

2024-04-03 05:51 UTC, HoeSeong123 approved these changes

2024-04-25 08:03 UTC, Wonmi91 commented
잘 읽었습니다 💜

2024-04-29 07:47 UTC, merged