레벨1 글쓰기 작성
woowacourse/woowa-writing pull request #135
Opened 2024-03-28 14:54 UTC by kelly6bf

2024-03-29 03:12 UTC, hwinkr reviewed
[한 페이지가 될 수 있게](https://www.youtube.com/watch?v=oYvgISKD5Y8)

2024-03-29 03:12 UTC, hwinkr commented on level-01.md
> +"제 인생의 아름다운 한 페이지가 되어주셔서 정말 감사합니다."
❤️

2024-03-29 04:53 UTC, pp449 commented
힘들땐 켈리 한잔 🍻

2024-03-29 12:04 UTC, hyeon0208 commented
켈리

2024-03-29 12:26 UTC, hyeon0208 commented on level-01.md
> +위 두 질문에 대해 필자가 질문을 받는다면 이렇게 답할 것이다. "yes", "이 글을 읽고 있는 당신들과 함께 하고 있으니까"
![image](https://github.com/woowacourse/woowa-writing/assets/99153215/695059a8-b7c4-40fe-ad10-6f7c0998b5c6)

2024-03-29 12:26 UTC, hyeon0208 commented on level-01.md
> +코드가 원하는대로 나오지 않아도 상관없다. 내 부족한 부분을 함께 찾아주고 다듬어 줄 당신들이 있으니까.
멋있는 말이네요 👍🏻

2024-03-29 12:26 UTC, hyeon0208 commented on level-01.md
> +"제 인생의 아름다운 한 페이지가 되어주셔서 정말 감사합니다."
🎶 지금 이 순간이 다시 넘겨볼 수 있는 한 페이지가 될 수 있게 🎶

2024-03-29 12:26 UTC, hyeon0208 commented on level-01.md
> +조금씩 첫날의 설램은 사라지고 다시금 모래들이 밟히기 시작했다. 정신을 차려보니 난 다시 사막 한 가운데에 있었다.
공감가네요 ..
레벨1은 시간 넉넉하다는 말을 많이 봐서 "프리코스 난이도겠지 ~"라 생각해 추가로 공부할 내용을 계획했었어요.
근데 미션을 거듭할 수록 "내가 많이 부족한 걸까"라고 생각이 들다 정신을 차려보니 사막 한 가운데더라구요 🥲

2024-03-31 16:54 UTC, robinjoon reviewed
안녕 켈리! 로빈이야! 데일리 조 크루들이 어떤 생각을 하고 지냈는지 궁금해서 이렇게 한명 한명 찾아가서 리뷰를 달고 있어.

> 인생을 즐기는건 무엇일까? 남들에게 인정 받는 삶을 사는것이 그 해답일까? 그럼 남들에게 인정받기 위해서는 무엇을 해야할까? 좋은 회사? 높은 연봉?
> 열심히 걷고 있는 이 **사막**끝에, 정말 내가 원하는게 있을거라는 확신은 없었다.

켈리가 우테코에 오기 전에 했던 생각들은 전형적인 20대 중반 청년들이 하는 고민인 것 같아. 특히 우리나라는 인격이 형성될 무렵부터 다른 사람들과 비교하며 경쟁하는 것을 가르치니까, 더 심각하게 받아들여지는 것 같아. 이런 것으로부터 벗어나는 것을 사막에서 나가는 것으로 비유한 부분이 참 인상깊었어.

> "제 인생의 아름다운 한 페이지가 되어주셔서 정말 감사합니다."

켈리의 인생이라는 책, 아름답게 써내려가길 바래!

2024-03-31 16:54 UTC, robinjoon commented on level-01.md
> +
짧은 시간에 쓴 글이라고 생각되지 않을 만큼 잘 읽히는 글이었던 것 같아! 👍

2024-03-31 16:54 UTC, robinjoon commented on level-01.md
> +# 당신의 인생을 즐기고 있나요?
그때 했던 질문이 복선이었다니.. 역시 켈리

2024-03-31 16:54 UTC, robinjoon commented on level-01.md
> +조금씩 첫날의 설램은 사라지고 다시금 모래들이 밟히기 시작했다. 정신을 차려보니 난 다시 사막 한 가운데에 있었다.
사막이라는 표현 정말 멋있다..

2024-03-31 16:54 UTC, robinjoon commented on level-01.md
> +레벨1 매주 월요일, 조금은 장난스럽게 작성했던 고민들을 해결할 수 있었던건 당신들이 있었기에 가능했다. 근 2년동안 날 괴롭혔던 막막함을 빠르게 풀 수 있었던 것도 당신들이 있었기에 가능했다.
당신이 누구를 지칭하는 건지 알기 어려운 것 같아! 이 글을 읽는 독자를 말하는걸까? 아니면 매주 월요일이니까 유연성 강화 스터디 같이 하는 연극조? 아니면 다른 우테코 구성원들 모두를 지칭하는 건가?

물론, 어떤 것이든 다 말이 되고 이를 해석하는 재미도 있긴 해서 괜찮은 것 같기도 해.

2024-03-31 16:54 UTC, robinjoon commented on level-01.md
> +처음 우테코에 입학한 2 ~ 3일동안은 정말 미칠듯한 도파민과 함께하였다. 출근길이 즐거웠고, 잠실의 공기는 너무나도 좋았다. 인생을 즐긴다는건 이런걸까? 이제야 사막에서 나갈 수 있을거 같다.
그래서 춤을 춘거구나 ㅋㅋㅋㅋㅋ

2024-04-01 05:13 UTC, healim01 reviewed
안녕하세요 켈리! FE 크루 헤일리입니다! 🍀

켈리의 감동적인 글을 너무 잘 읽었습니다! 급하게 쓰셨다는 말과 달리 정말 감동적이고 흡입력있는 글이었던거 같아요! 어쩌면 오히려 너무 많은 검열과 수정이 없어서 더 이러한 느낌의 글이 나올 수 있었지 않을가도 싶네요! 정말 잘읽었습니다! 
특히 본인이 이전에 처했던 상황을 사막으로 표현한 부분이 재밌었습니다! 켈리는 데일리조 미팅을 통해서 정말 좋은 사람들을 만난거 같네요. 그들과 함께 이 사막을 이겨내서 바다를 만날 수 있었으면 좋겠습니다! 

다른 캠퍼스에 계셔서 뵙지는 못했지만 슬랙이나 줌을 통해서 종종 뵈었었는데 이렇게 글로 만나뵈게 되니 또다른 켈리분의 모습을 본거 같네요! 글쓰기 수고 많으셨습니다!!

2024-04-01 05:13 UTC, healim01 commented on level-01.md
> +"제 인생의 아름다운 한 페이지가 되어주셔서 정말 감사합니다."
정말 감동적인 멘트네요..🥹

2024-04-01 05:13 UTC, healim01 commented on level-01.md
> +정말 뜬근없이 생겨난 작은 욕심을 시작으로 점차 내 마음가짐이 달라지기 시작했던거 같다. 늘 쫒아왔던 막연한 목표가 아닌 소소한 욕심들을 채워나가기 시작하면서 그 과정의 즐거움에 빠지게되었다.
번아웃이 올 때에는 잠시 그곳에서 벗어나서 새로운 공간을 탐색하는 것이 매우 좋다고 하더라구요! 켈리는 이를 활용하여 새로운 즐거움을 찾으셨네요!

2024-04-01 06:50 UTC, Hogu59 reviewed
켈리 안녕하세요!
안드로이드 6기 크루 악어 🐊 입니다!

짧은 시간에 썼다는게 안 믿길만큼 구성이 짜임새 있고 정갈하네요 😄 
사막에 비유한 내용을 읽으니 마치 어린왕자를 읽고 있는 느낌이라 색다른 경험이었습니다.

분야가 다르지만, 제가 볼때 켈리는 이미 미션을 잘 하고 있지 않나 싶은데,,,ㅋㅋ
그럼에도 우리 모두가 같은 고민을 가지고 공감하고 있다는 점이 새삼 새롭게 다가오네요.

운전을 하다보면 수 km 의 터널을 지나갈 때가 있습니다.
아무리 가도 끝이 보이지 않는데, 출구가 보이지 않는 터널에서 나갈 수 있는 방법은 생각보다 간단합니다.
계속 나아가는 거죠.

제 앞에 보이는 켈리의 글은 그런 터널 속에서 여전히 한 걸음 나아가는 모습 같습니다.

레벨1 기간동안 고생 많으셨습니다.
즐거움을 찾으셨으니, 레벨2 동안에는 즐거움 속에서 즐거운 사람들과, 더 즐거운 성장이 되길 응원합니다 💪

2024-04-01 06:50 UTC, Hogu59 commented on level-01.md
> +열심히 걷고 있는 이 사막끝에, 정말 내가 원하는게 있을거라는 확신은 없었다. 하지만 그렇다고 잠시나마 멈춰 주변을 둘러볼 자신도 없었다. 그 잠깐의 멈춤으로 길을 잃게 될까봐.
`그 잠깐의 멈춤으로 길을 잃게 될까봐.` 참.. 가슴이 먹먹해지도록 공감이 되는 말이네요.
휴식이 필요하지만, 오히려 그 휴식을 받아들일 수 없는.. 마치 휴식에 대한 거식증 같은 우리 모두가 공감할 수 있는 말이네요. 😢

2024-04-02 04:08 UTC, HoeSeong123 reviewed
우테코 생활을 정말 잘 즐기시는 것이 보입니다 켈리 
모르는 사람에게 선뜻 말을 건네는 것은 정말 어려운 일인데 대단하네요..
덕분에 저도 즐거운 우테코 생활이 될 것 같습니다.
레벨 1도 즐거웠지만 앞으로의 생활들이 기대가 되네요.

글 잘 읽었습니다😄

2024-04-02 04:31 UTC, zangsu requested changes
안녕하세요 켈리, 글 정말 재미있게 읽었어요.
켈리랑은 많이 대화를 나눠 봐서 그런지, 새로운 켈리의 모습을 보는 대신 켈리에게 들었던 과거의 켈리를 더 자세히 만나볼 수 있었던 것 같아서 재미있었어요!
짧은 의견들 첨부했으니 확인 부탁드립니다!

2024-04-02 04:31 UTC, zangsu commented on level-01.md
> +만약 이 글을 읽는 당신이 제목과 같은 질문을 받으면 어떤 답변을 줄 수 있겠는가? 수많은 답변이 나올 수 있겠지만 대게는 "yes" 혹은 "no"라는 답변을 내놓을 거라고 생각한다.
"답변을 준다" -> "대답을 한다" 가 더 자연스러울 것 같아요.
아니면, 이렇게 작성을 한 이유가 있을까요?

2024-04-02 04:31 UTC, zangsu commented on level-01.md
> +그런 생각들을 하며 캠퍼스에 도착했을 때, 그날은 유독 아무것도 하기 싫었다. 그래서 정말 아무것도 하지 않았다. 정말 이상하게도 에디터를 보고 싶지 않았다. 하루를 낭비하는거 같아 마음이 아팠다.
```suggestion
그날은 유독 아무것도 하기 싫었다. 그래서 정말 아무것도 하지 않았다. 정말 이상하게도 에디터를 보고 싶지 않았다. 하루를 낭비하는거 같아 마음이 아팠다.
```
앞의 문장이 없더라도 충분히 글은 잘 이해가 되는 것 같아요!

2024-04-02 04:31 UTC, zangsu commented on level-01.md
> +물론 내 목표는 여전하다. 여전히 좋은 기업에 가고 싶고 사람들에게 인정도 받고싶다. 하지만 이제 그것만을 바라보며 숨가쁘게 달려나가고만 싶지는 않다. 앞만보고 달리기에는 내 주변 풍경들이 너무 아름답다.
빠르게 앞으로 달려가는 것도, 조금은 천천히 걸으면서 주변의 풍경을 즐기는 것도 모두 삶을 대하는 각자만의 멋있는 방식이라 생각해요! 
주변 풍경의 아름다움을 알아볼 수 있는 켈리가 정말 멋있네요 :)

2024-04-02 04:31 UTC, zangsu commented on level-01.md
> +"제 인생의 아름다운 한 페이지가 되어주셔서 정말 감사합니다."
고작 한페이지만 할당시켜 주는건가요? 저는 조금 더 욕심이 나는걸요 :(

2024-04-02 07:22 UTC, healim01 approved these changes

2024-04-02 08:24 UTC, hjk0761 commented
켈리, 안녕하세요! 같은 데일리조 무빈입니다!

켈리와 함께했기에 데일리 미팅을 더욱 즐길 수 있었습니다!
인생을 즐길 수 있다는 당당한 말 한마디 배워갑니다!
내가 걷는 이 길이 사막인지 빙판인지는 내가 마음먹기에 달린 것 같습니다 ㅎㅎ
인지하지 않고 걷는다면 나에게 편한 길이 되지 않을까요!

레벨 1도 고생 많았습니다!

2024-04-03 02:07 UTC, hyeon0208 approved these changes

2024-04-03 04:59 UTC, hwinkr approved these changes
코멘트 달고 싶어서 놀러왔는데, 달면 approve를 해줘야 했군요..ㅋㅋㅋㅋㅋ 🍺🍺🍺

2024-04-03 04:59 UTC, HoeSeong123 approved these changes

2024-04-03 05:00 UTC, robinjoon approved these changes

2024-04-03 05:06 UTC, zangsu approved these changes
켈리가 지금 걷는 길이 사막이면 어떻고, 가시밭길이면 또 어때요?
앞으로 같이 걸어가봐요 :)
누가 알아요, 그 끝에 신기루가 아닌, 진짜 오아시스가 있을지?!
글쓰기 미션 고생하셨습니다!

2024-04-03 05:50 UTC, jinchiim approved these changes

2024-04-25 08:31 UTC, Wonmi91 commented
잘 읽었습니다 💜

2024-04-29 07:47 UTC, merged