[레벨 2 글쓰기 미션] 러쉬(이태훈) 미션 제출합니다.
woowacourse/woowa-writing pull request #188
Opened 2024-06-05 01:41 UTC by xogns1514

안녕하세요 여러분~ 러쉬입니다🏈
레벨2 글쓰기 작성해보았습니다.
주제는: 왜 유연성 강화 목표를 잡지 못했을까? 입니다.
부족한 부분 가감없이 피드백 부탁드립니다.

천천히 리뷰 남겨주세요!
[편하게 보기](https://github.com/woowacourse/woowa-writing/blob/e144be05c01d5fa2d9d1da05fd45c75a0cb51b15/level2.md)

2024-06-07 11:25 UTC, jinhokim98 requested changes
안녕하세요! 러쉬(백태훈ㅋㅋㅋ)
이미 유연한 러쉬 부럽네요ㅋㅋㅋ 단점이 없다 와우
글 잘 읽었습니다! 몇 가지 코멘트 적었는데 참고 부탁 드립니다!! 홧팅

2024-06-07 11:25 UTC, jinhokim98 commented on level2.md
> +지속적으로 생각하다 보니, 장점과 단점을 점점 알게 되었다. 자신의 장점과 단점을 알고 있다는 점에서, 자기 객관화가 가능한 사람이라고 생각한다.
구체적으로 어떤 생각을 했는지 예시를 적어도 좋을 것 같아요. 어떤 상황에서 나는 어떤 사람일까? 나는 이럴 때 어떤 감정이 느껴지고, 어떻게 대처하는 사람인지 이런 느낌으로!

2024-06-07 11:25 UTC, jinhokim98 commented on level2.md
> +가끔 예상하지 못한 일정이 생기곤 하지만, 루틴을 크게 망가뜨릴만한 이벤트가 발생하지는 않는다. 즉, 외부 변화가 크게 일어나지 않는다. 항상 비슷한 환경속에서 일상을 보내기 때문에 불편함을 느낄 일도 적다.
루틴을 망가뜨릴만한 이벤트에서 조금 작게 생각해서 내가 어떤 상황을 마주했을 때 당황스러웠는지 그런 순간들을 기억해내다 보면 아이디어가 나올 수 있지 않을까요?

2024-06-07 11:25 UTC, jinhokim98 commented on level2.md
> +이전까지의 생각의 흐름을 정리해 결론을 내리자면, 현재의 나는 유연한 사람이다. 강화의 필요성을 느끼는 불편함을 못 느끼고 있고, 가장 큰 원인은 외부 변화가 적은 환경에 적응되어 때문이다.
```suggestion
이전까지의 생각의 흐름을 정리해 결론을 내리자면, 현재의 나는 유연한 사람이다. 강화의 필요성을 느끼는 불편함을 못 느끼고 있고, 가장 큰 원인은 외부 변화가 적은 환경에 적응되어 있기 때문이다.
```

2024-06-08 06:05 UTC, JiHyeonL reviewed
안녕하세요 러쉬! 러쉬의 level2 첫 페어였던 레모네 입니다 😄 

저도 level2에 들어서서 유연한 사람이 되었다고 생각했는데 러쉬의 글을 읽고나니 과연 익숙하지 않은 상황에서도 유연하게 대응할 수 있을지 생각해 보게 되네요ㅎㅎㅎ

"함께 유연해지기" 단락도 인상깊었어요. 저는 유연성 강화 스터디를 통해 사람들이 어떤 방식으로 조언과 위로를 건네는지 배울 수 있었거든요. 스스로의 유연성을 기르는 것을 넘어서, 더 많은 것을 스터디에서 얻었기 때문에 러쉬의 글에 공감이 많이 됐어요.

전체적으로 글에 러쉬의 생각이 잘 담겨있고, 문장도 깔끔해서 간단한 피드백 하나 남겼습니다!

글 작성하느라 수고 많으셨습니다 👍

2024-06-09 11:11 UTC, unifolio0 approved these changes
개인적으로 저는 유강스의 목적은 `단점을 고치는 것`이 아닌 `나 자신을 아는 것`이라고 생각해요. 이 기준으로 보면 러쉬의 글은 유연성 넘치는 글이네요. 👍

그래도 다른 사람에게 피드백을 하는 과정을 통해 유강스를 긍정적으로 인식해서 다행이네요.

글 잘 읽고 갑니다!

2024-06-09 11:11 UTC, unifolio0 commented on level2.md
> +어디까지나 현재의 나에게 없는 것이다. 앞으로 나의 유연하지 못한 부분을 찾아가는 과정에 서있다고 생각한다. 수많은 변화를 겪게 될 것이고, 그 속에서 새로운 모습을 발견할 것이라고 확신한다.
`어디까지나 현재의 나에게 없는 것이다.`에 대한 설명이 부족한 것 같아요. 조금 더 설명해주면 좋을 것 같아요!

2024-06-10 11:11 UTC, 00kang reviewed
러쉬 안녕하세요~ FE 초코🍫입니다. 글 잘 읽었습니다 :>

이미 본인에 대해 많은 고민을 했던 만큼, 굳이 새로운 목표를 찾지 않고 유연성에 대한 생각을 작성해주신 게 인상깊어요. 
전반적으로 잘 써주셔서 간단한 코멘트만 남겨요.

2024-06-10 11:11 UTC, 00kang commented on level2.md
> +지속적으로 생각하다 보니, 장점과 단점을 점점 알게 되었다. 자신의 장점과 단점을 알고 있다는 점에서, 자기 객관화가 가능한 사람이라고 생각한다.
`스스로 자기 객관화가 되는 사람이라고 생각한다` 문장은 없애는 게 어떨까요?

 이 앞의 `즉, 자기 객관화가 되는 상태이어야 한다. `와 혼돈을 줄 수 도 있고, 
`~점에서, 자기 객관화가 가능한 사람이라고 생각한다. `라는 문장이 있어서 없어도 될 것 같다는 제안 드려요!

2024-06-10 11:11 UTC, 00kang commented on level2.md
> +어디까지나 현재의 나에게 없는 것이다. 앞으로 나의 유연하지 못한 부분을 찾아가는 과정에 서있다고 생각한다. 수많은 변화를 겪게 될 것이고, 그 속에서 새로운 모습을 발견할 것이라고 확신한다.
레모네가 추천한 문장처럼 앞 뒤 맥락을 잇는 문장이 있으면 좋을 것 같아요!

2024-06-11 02:03 UTC, 00kang approved these changes

2024-06-11 03:55 UTC, eun-byeol approved these changes
러쉬 안녕하세요! BE 조조입니다.

러쉬만의 솔직한 글 잘 읽었습니다! 유강스 목표를 찾지 못한 이유에 대해 깊게 고민하신 것 같아요. 러쉬만의 생각과 결론을 존중합니다! 제가 더 리뷰드릴 부분은 없을 것 같아요.

> 앞으로 나의 유연하지 못한 부분을 찾아가는 과정에 서있다고 생각한다. 수많은 변화를 겪게 될 것이고, 그 속에서 새로운 모습을 발견할 것이라고 확신한다.

변화를 정면으로 맞이하고 계시네요. 앞으로 어떤 일이 있든 잘 해내실 것 같아요. 지금처럼, 긍정적인 모습으로 우테코의 생활을 잘 마무리하시길 응원하겠습니다🙌 다음 시리즈도 기대하겠습니다!

2024-06-11 03:55 UTC, eun-byeol commented on level2.md
> +유연성 강화 훈련 주차가 지날수록 모두 유연해지고 있다는 것을 느꼈다. 그래서 나의 유연성 강화 목표를 제대로 찾지 못하더라도, 활동 자체는 의미있었다.
단점을 통해 유강스 목표를 설정하지 못했다면,
다른 크루들의 목표에서 찾아보는 건 어떨까요? 러쉬의 단점이 아닐지라도, 이상향에 가깝다면 더 강화해 볼 수 있을 것 같아요!

2024-06-11 03:55 UTC, eun-byeol commented on level2.md
> +불편함을 못느낀 이유로 루틴화된 일상을 의심했다. 나는 루틴화된 삶을 선호하는 사람이다. 우테코의 생활은 루틴화된 삶을 살기에 최적화돼있다. 같은 시간에 기상, 학습, 운동, 취침의 일상이 반복된다.
저도 루틴화된 삶을 지향해서 공감이 돼요.
무던한 편이기도 하고요. 이게 제 단점이라고 생각했는데, 러쉬 글을 읽어보니 오히려 유연성이 있다고 생각할 수 있겠네요👍

2024-06-11 03:55 UTC, eun-byeol commented on level2.md
> +유연성 강화 목표를 찾지 못한 이유와 '현재의 나는 유연한가?'에 대해 고찰하려 한다.
유강스 목표가 `유강스 목표 설정하기` 였을까요?🤔

2024-06-11 09:47 UTC, ss0526100 approved these changes
안녕하세요~ FE 소파입니다.

스스로 유연성을 정의한 후, 본인의 유연성에 대해서 확인해보는 과정의 글을 써주셨네요!

논리적으로 유연성을 정의하신 것 같아 인상 깊게 느껴졌습니다. 

저는 러쉬가 여러가지 방식으로 유연성을 정의해보면 좋을 것 같다는 생각도 들었어요.

하나의 수학 문제를 여러 방식으로 정의해서 풀어보면 새로운 영감이 느껴질 때가 있잖아요? 그것처럼 새로운 통찰을 발견할 수도 있을 것 같다는 생각이 들었어요.

고생하셨습니다!! 어프루브 드릴게요!!

2024-06-12 02:22 UTC, dwax1324 approved these changes
안녕하세요 러쉬, 글 잘보았습니다.
글이 짜임새가 있어서 읽기가 아주 편했어요.

불편함을 찾지 못한 이유를  찾기 위해서 유연함이 무엇일까부터 정의하는 과정이 흥미로웠습니다.
하나의 문제 해결 과정을 보는 것 같았어요. 

자기객관화에서 시작해서 루틴화까지 도달한 과정도 멋졌고, 
이를 통해 유의미한 결론을 도출해냈으니 엄청난 수확이 아닐까요?

그냥 불편함이 없다고 느끼는 것과 진지하게 고민 해봤을 때 불편함이 없다고 느끼는건 다르다고 생각해요.
러쉬는 후자의 경우 같고 자기 성찰이 굉장히 잘되는 사람이라는걸 글에서 느꼈습니다.

레벨3 때는 많은 상황의 변화가 일어날 거 같은데, 러쉬는 어떻게 대처할지 지켜봐야겠습니다. 👀 ㅋㅋ
레벨2 고생하셨고, 항상 많은 영감을 줘서 감사해요!

2024-06-12 02:22 UTC, dwax1324 commented on level2.md
> +앞으로 만날 변화들에 대해 반갑게 맞이하고, 강화하여 한층 더 유연한 사람으로 성장하고 싶다.
러쉬가 앞으로 어떤 변화들을 만나고 어떻게 변화할지 기대됩니다.
변화를 맞이할 준비가 된 사람과, 준비가 되지 않은 사람의 차이는 극명한거 같습니다.
옆에서 봤을 때 러쉬는 무게 중심이 있어서 어떠한 변화가 생겨도 흔들릴지 언정 부러지지는 않을 것 같아요.
흔들림 속에서 더욱 강인해지고 새로운 모습을 발견하게 될 러쉬, 응원합니다!

2024-06-12 04:17 UTC, JiHyeonL commented
안녕하세요 러쉬!
벌써 글쓰기 마지막 날이네요 😄 
approve를 늦게 드려 일정에 차질이 생길까봐 먼저 approve 하겠습니다!  
수고하셨습니다 👍

2024-06-12 04:17 UTC, JiHyeonL approved these changes
안녕하세요 러쉬!
벌써 글쓰기 마지막 날이네요 😄 
approve를 늦게 드려 일정에 차질이 생길까봐 먼저 approve 하겠습니다!  
수고하셨습니다 👍

2024-06-12 04:30 UTC, xogns1514 commented on level2.md
> +우테코 생활 동안 위에서 언급한 문제점을 제외하면 없는 것 같다. 왜 다른 불편함을 느끼지 못했을까?
단점이 여러개 있겠지만, 단점들중에 불편함을 느끼는 단점과 안느끼는 단점이 있는 것 같네요. 
단점으로 인해 문제점이 생기고, 문제점에 대한 불편함을 느꼈던 것 같습니다.

2024-06-12 04:30 UTC, xogns1514 commented on level2.md
> +불편함을 못느낀 이유로 루틴화된 일상을 의심했다. 나는 루틴화된 삶을 선호하는 사람이다. 우테코의 생활은 루틴화된 삶을 살기에 최적화돼있다. 같은 시간에 기상, 학습, 운동, 취침의 일상이 반복된다.
상황에 대해 빠르게 나의 습관을 만들고 익숙해지는 것도, 유연한 대처 중 하나인 것 같아요ㅎㅎ

2024-06-12 04:30 UTC, xogns1514 commented on level2.md
> +불편함을 못느낀 이유로 루틴화된 일상을 의심했다. 나는 루틴화된 삶을 선호하는 사람이다. 우테코의 생활은 루틴화된 삶을 살기에 최적화돼있다. 같은 시간에 기상, 학습, 운동, 취침의 일상이 반복된다.
개인적으로 반복되는 행동을 통해 안정감을 느끼는 것 같습니다. 개인마다 루틴화된 일상이 안정감을 주는 여부는 다를 것 같아요

2024-06-12 04:30 UTC, xogns1514 commented on level2.md
> +가끔 예상하지 못한 일정이 생기곤 하지만, 루틴을 크게 망가뜨릴만한 이벤트가 발생하지는 않는다. 즉, 외부 변화가 크게 일어나지 않는다. 항상 비슷한 환경속에서 일상을 보내기 때문에 불편함을 느낄 일도 적다.
레벨1 글쓰기에서 작성한 경험인, 운동을 못하게 되어 루틴이 망가진 경험이 있는데요.
활동적인 행동을 하지 않으면, 엄청 스트레스를 받는다는 것을 느낀적이 있습니다. 
따라서 일상 중간중간 운동등을 껴넣는 방법으로 스트레스를 해소해야겠구나라고 결심했습니다ㅋㅋ
다른 상황에 대해서도 생각해봐야겠네요!

2024-06-12 04:30 UTC, xogns1514 commented on level2.md
> +유연성 강화 훈련 주차가 지날수록 모두 유연해지고 있다는 것을 느꼈다. 그래서 나의 유연성 강화 목표를 제대로 찾지 못하더라도, 활동 자체는 의미있었다.
좋은 아이디어네요! 다른 크루로 부터 영감을 얻을 수도 있겠어요

2024-06-12 04:50 UTC, jinhokim98 approved these changes
오케이~ approve 드립니다!
고생 많았어요ㅎ

2024-06-12 06:18 UTC, hyxrxn approved these changes
아토입니다!

이해가 잘 되고, 개인적으로 많이 동의하게 되는 글이네요.
혹시 우테코 중, 러쉬가 유연하지 못한 상황을 알게되어 목표를 세운다면 저에게도 알려주면 좋겠어요 ㅋㅋㅋㅋ
저도 그런 상황을 맞닥뜨린다면 러쉬에게 조언을 구하러 가겠습니다.

글 잘 읽었습니다!

2024-06-12 06:18 UTC, hyxrxn commented on level2.md
> +### 루틴화
저는 루틴이 별로 없어서 루틴화가 러쉬의 주제와 어떤 관련이 있을지 궁금했는데,
이 문단을 끝까지 읽으니 이해가 되네요.

저도 갑자기 새로운 (그리고 힘든) 상황에 놓여보지 않아서 지금은 유연성 강화 목표로 삼을 게 없는 것 같기도 해요!

2024-06-12 06:18 UTC, hyxrxn commented on level2.md
> +이는 레벨1부터 쭉 느껴오던 감정이다. 크루들의 고민들이 점점 해결되는 과정을 관찰하는 것이 재미있었고, 그 과정속에 내가 기여할 수 있다는 점이 뿌듯했다.
동의합니다!

물론 주변 크루들이 유연해져가는 길목에 제가 함께 했다는 것도 좋았지만,
다른 크루들이 유연하지 못하다고 느끼는 부분이 나는 왜 괜찮은지 알아가는 것도 자기 객관화에 도움이 되었다고 생각해요.

2024-06-12 06:18 UTC, hyxrxn commented on level2.md
> +현재의 나는 유연하지 못한 부분을 찾아가는 과정에 서있다고 생각한다. 수많은 변화를 겪게 될 것이고, 그 속에서 새로운 모습을 발견할 것이라고 확신한다.
이 부분도 제 생각과 아주 비슷하네요.
언젠가 유연하지 못한 상황을 맞닥뜨린다면, 그 때 지금의 유강스 경험이 큰 도움이 되겠죠?

2024-07-31 02:14 UTC, merged