[2레벨 글쓰기 미션] 로빈(임수빈) 제출합니다.
woowacourse/woowa-writing pull request #209
Opened 2024-06-05 05:51 UTC by robinjoon

이번 유연성 강화 목표인 짜증내지 않기를 달성하기 위한 과정을 적어봤습니다.

이전 글과 이어지게 하기가 여간 쉽지 않네요... 그래서 그건 포기했습니다! ㅎ

2024-06-05 10:34 UTC, BurningFalls commented on level2.md
> +자연스럽게 나의 유연성 강화 목표는 짜증내지않기가 되었다.
자신의 단점을 자각한다는게 결코 쉽지 않은 것인데(그것이 맞았든 틀렸든지 간에), 그걸 해낸 로빈은 대단한 사람인 것 같네요!

2024-06-05 10:44 UTC, BurningFalls commented on level2.md
> +하지만, 욕구의 기준치를 낮추는 것은 그리 쉬운 일이 아니다. 자칫 잘못하면 자기합리화나, '내가 그러면 그렇지 뭐…' 와 같이 자존감을 깎는 일이 될 수 있다.
'자기합리화'는 정말 무서운 단어라고 생각합니다. 자기합리화를 하고 있는 본인은 그게 자기합리화인지 알아차릴 방법이 없죠. 다른 사람들과 내 고민에 대해서 대화를 많이 나누어보는 것이 해결책이라고 생각합니다.

2024-06-05 10:45 UTC, BurningFalls commented on level2.md
> +물론 부정적인 상황에서 긍정적인 점을 찾는 것 자체가 쉬운 일은 아니다. 그래서 더 해볼 가치가 있다고 생각했다.
저는 부정적인 사고를 아무리 긍정적으로 바꾸려고 해도 잘 안되던데, 그걸 잘하는 사람들을 보면 굉장히 신기합니다.

2024-06-05 10:47 UTC, BurningFalls commented on level2.md
> +그리고, 짜증이 덜 나니 자연스럽게 리뷰어의 사정을 이해할 수 있는 여유가 생겼다.
저는 부정적인 사고를 아무리 긍정적으로 바꾸려고 해도 잘 안되던데, 그걸 잘하는 사람들을 보면 굉장히 신기합니다. 로빈의 글을 읽어보니 짜증을 덜 일으키는데 굉장한 도움이 된 것 같네요!

2024-06-05 10:48 UTC, BurningFalls commented on level2.md
> +그럼에도 때로는 논리적인 근거보다 그저 아무 이유 없이 믿는 것이 더 좋을 때도 있지 않을까? 오늘도 더 나은 미래가 있을 것이라 믿고 최선을 다해 살아가는 것이 마음의 여유를 찾는 유일한 방법일 것 같다.
미래의 나는 오늘의 나보다 반드시 한층 더 성장해 있을 것이기 때문에, 미래의 나에게 미래를 맡기는 것도 좋은 방법이라고 생각합니다!

2024-06-05 10:51 UTC, BurningFalls commented on level2.md
> +레벨 3에서의 유연성 강화 목표는 이걸로 해야겠다. 짜증을 들어내지 않기!
로빈의 LEVEL2 글의 첫 단락을 읽을 때부터 짜증이 나는 것과 짜증을 드러내는 것은 다르지 않을까하는 의문이 들었습니다. 끝 단락을 읽으니 로빈도 이를 제대로 인지한 것 같네요.

2024-06-05 10:53 UTC, BurningFalls reviewed
안녕하세요, 로빈! 폭포입니다.

본인의 단점을 인지하고 이를 어떻게 하면 고칠 수 있을지에 대한 방법을 찾아나가는 모습이 인상적이네요! 더 좋은 방향으로 바뀌어나가는 로빈의 모습 앞으로도 계속 기대하겠습니다.

글 잘 읽었습니다. 😄

2024-06-05 11:11 UTC, fromitive commented on level2.md
> +실험 계획 세우기라는 이름으로 한 활동은 사실 큰 도움이 되지 않았다. 오히려 그보다는 학습하듯이 내가 짜증 나는 이유를 스스로 생각하여 가설을 세우고 입증하는 것이 더 효과적이었다.
실험 계획 세우기 즉 가설을 세우고 관찰하고 그 결과가 어떠한지 기록하여 입증하는 것이라고 생각하는데요

로빈이 생각하는 실험 계획 세우기와 로빈의 학습 방식의 차이가 어떤지 잘 이해가 가지 않아요 😢 혹시 구체적으로 표현해주실 수 있을까요?

2024-06-05 11:18 UTC, fromitive commented on level2.md
> +짜증은 이 불만족 수치가 임곗값을 넘었을 때 발생한다. 그리고 그 임곗값을 결정하는 것이 마음의 여유다.
이 표현을 간단한 표나 그래프로 표현해보는건 어떨까요?

불만족 수치의 총량이 1인 것 일까요?

2024-06-05 11:23 UTC, fromitive commented on level2.md
> +그럼에도 때로는 논리적인 근거보다 그저 아무 이유 없이 믿는 것이 더 좋을 때도 있지 않을까? 오늘도 더 나은 미래가 있을 것이라 믿고 최선을 다해 살아가는 것이 마음의 여유를 찾는 유일한 방법일 것 같다.
불확실한 미래에 대해 로빈이 바라보는 태도가 좋네요 👍 그럼에도 불구하고 최선을 다해 살아가는 것! 잘 해쳐나가봐요

2024-06-05 11:27 UTC, fromitive commented on level2.md
> +레벨 3에서의 유연성 강화 목표는 이걸로 해야겠다. 짜증을 들어내지 않기!
짜증을 들어내지 않는 것 어렵죠 ㅋㅋ

저는 그래서 짜증을 덜내기 위해서 적어도 6시간 자거나, 러닝으로 생각을 비워내는 활동들을 하고 있어요
이런 활동들을 하다보니 `건강한 정신은, 건강한 육체에서 나온다`라는 말에 많이 공감이 갔어요.

로빈도 운동하기 위해서 러닝하는 모습 간간히 뒤에서 지켜봤는데, 자신의 좋지 않은 점을 인지하고 다른 크루들에게 드러내고 이렇게 고치려고 노력하는 모습이 정말 멋있습니다 👍

2024-06-05 11:28 UTC, fromitive commented on level2.md
> +물론 부정적인 상황에서 긍정적인 점을 찾는 것 자체가 쉬운 일은 아니다. 그래서 더 해볼 가치가 있다고 생각했다.
부정적으로 느껴진다면 "그럼에도 불구하고"를 마음속으로 외쳐본다면 좀 더 찾기가 쉬워질거에요 🙂

2024-06-05 11:39 UTC, fromitive commented
로빈! 글 잘 읽었어요!

레벨1 데일리조로서 레벨2 글을 보면서 로빈은 이전 레벨의 로빈보다 훨씬 많이 성장했고, 자신의 단점을 잘 파악하려고 애쓰는걸 알게되었어요. 이 단점들을 계속 고치려는 노력하는 과정이 잘 녹여있어서 재밌게 읽었어요 🙂

2024-06-08 03:02 UTC, jinyoung234 commented on level2.md
> +짜증이 난다는 것은 원하는 대로 이루어지지 않는 것에 대해 화가 나는 것이기 때문이다. 구체적으로 짜증 수치는 여러 방면의 욕구 만족도의 가중치가 부여된 합이라는 가설을 세웠다.
짜증 = 욕구 불만족 이라고 정의를 해주셨는데, 혹시 로빈은 어떤 순간에서 불만족스러움을 마주했는지를 이야기 해주셨다면 더 공감할 수 있었을거 같아요  .. !

2024-06-08 03:03 UTC, jinyoung234 commented on level2.md
> +하지만, 욕구의 기준치를 낮추는 것은 그리 쉬운 일이 아니다. 자칫 잘못하면 자기합리화나, '내가 그러면 그렇지 뭐…' 와 같이 자존감을 깎는 일이 될 수 있다.
합리화는 확실히 '해결'보단, '체념'에 가까운거 같아요 🥲

2024-06-08 06:05 UTC, jinyoung234 commented on level2.md
> +레벨 3에서의 유연성 강화 목표는 이걸로 해야겠다. 짜증을 들어내지 않기!
유연성 강화 목표를 `짜증 드러내지 않기`라고 설정한 것도 로빈이 조금 더 유연해졌다는 증거가 되는 것 같아 보기 좋네요 🥹👍

2024-06-08 06:10 UTC, jinyoung234 reviewed
안녕하세요 로빈 😉 프론트엔드 크루 지니 입니다!

로빈의 이야기를 들으며, `부정적인 감정을 드러낸다.`를 인지하고 이를 극복하기 위해 `원영적 사고`를 생각하기도, 유연성 강화 목표를 설정하는 것도 인상적 이었던거 같습니다 ☺️☺️

저도 상담을 받으며, 이런 얘기를 들었었는데요.

> 부정적인 상황에서 부정적인 감정을 느끼는 것은 당연하다. 다만, 이 감정을 잘 포장해서 좋은 방향으로 나아가는 것도 관계에 있어서 중요하다.

로빈도 유연성 목표를 잘 세워주신 만큼 이런 감정을 마주 했을 때 로빈만의 방법으로 잘 극복해낼 수 있었으면 좋겠네요!

level2 글쓰기도 고생 많으셨습니다 !! 😆

2024-06-09 12:37 UTC, Largopie reviewed
안녕하세요! 로빈 :) 낙타🐫입니다!

로빈께서 이전 글과 이어지게 하기 어렵다고 하셨어요! 하지만 제가 레벨1 글쓰기와 같이 읽어보았는데, 시간의 흐름 자체가 레벨2 글쓰기의 도입부와 이어지게 작성한 것 같아서 저는 개인적으로 잘 이어졌다는 생각이 들었어요!

'짜증내지 않기'라는 목표 자체가 생각하기에 단점이라고 생각되는 부분을 정확하게 인지하고 있다는 뜻인 것 같아요! 메타인지를 정확히 했다는 증거이기도 한 것 같아서 정말 인상깊게 봤습니다 :)

더 나아가서 짜증은 날 수 있지만, 이를 올바르게 표현하는 방법을 목표로 설정하셔서 앞으로도 더욱 성장할 수 있다는 생각이 들어요!

멀다면 멀고, 가깝다면 가까운 앞으로의 우테코 생활 응원하겠습니다! 글 잘 읽었어요! 🍀

ps. 사소한 피드백 남겼으니 확인 부탁드립니다! 🐫

2024-06-10 07:00 UTC, donghoony requested changes
럭키비키 로빈 피드백 달러 왔습니다 🍀
유강스 진행하면서 점점 나아지는 모습이 보여서 기특(?)하네요 ㅋㅋㅋ 글에서도 어떤 방식으로 자신을 되돌아보는지를 확인할 수 있어 좋았습니다. 몇 가지 반영하면 좋을 사항을 남기니 확인해주세요!

2024-06-11 02:50 UTC, BurningFalls approved these changes

2024-06-11 07:11 UTC, jinyoung234 approved these changes

2024-06-11 07:46 UTC, ashsty approved these changes
안녕하세요, 로빈! 이번에 같은 데일리 조로 만나게 된 애쉬입니다!

로빈의 글은 1레벨 때도 그렇고 2레벨 때도 그렇고 술술 읽히네요. 글을 상당히 잘 쓰셔요! 테코톡 때 말씀하시는 것만 들어도 제법 재치 있는 분일 거라고 생각하고 있었는데 그런 면모가 글에서도 잘 드러나는 것 같네요. 👍

개인적으로 재미 있었던 건 로빈의 이번 글 주제가 유연성 강화 목표이되 - 개발과는 크게 관련 없는 주제였다는 거예요. 다른 크루들의 글은 대부분은 개발, 혹은 우테코 내부의 일과 관련되어 있는 글이었는데 로빈은 내면의 변화를 목표로 노력한 분투기를 써주셔서 더 재미있게 잘 읽은 것 같아요.

또 하나 공감 갔던 점을 꼽으라면... 저도 상당히 화나 짜증이 많은 편이라는 건데요 ㅋㅋㅋ

저도 제 그런 점을 고치고 싶어서 일부러 긍정적으로 말하고, 밝게 말하고, 또 생각하려고 노력하는 중이라 그런지 로빈이 어떤 점에서 불편을 느꼈고 또 개선하고 싶어했는지 알 것 같다는 생각이 들었어요. '나이 먹기==진짜 어른 되기' 라면 얼마나 좋을까요? 저는 어렸을 때 20살만 되면 자연스레 어른이 될 수 있을 거라고 생각했었는데요. 20살이 되자마자 얼마나 허무맹랑한 꿈을 꾸고 있었는지 깨달았지 뭡니까.

요는 더 나은 사람, 멋진 사람이 되려면 끊임없이 노력해야만 한다는 걸 저도 알게 된 지 얼마 되지 않았다! 다 같이 힘내보자! 하는 말이었습니다. 2레벨은 거의 끝나가지만 3레벨이 되어서도 럭키비키 마인드를 놓지 말자구용.

다사다난 2레벨도 고생하셨습니다!
방학 잘 보내시고, 다음 레벨도 함께 화이팅 해봐요~~!

무슨 어려운 일이 닥치더라도 전부 성장에 도움이 될 테니 완전 럭키비키잖아~ 🍀

2024-06-11 07:46 UTC, ashsty commented on level2.md
> +자신을 성찰해 본 결과, 유난히 내가 남들보다 쉽게 짜증을 낸다는 것을 알았다. 미션을 하다가도 짜증을 내고, 크루들끼리 농담을 할 때도 가끔 발끈하는 경우가 있었다.
어떤 경로로 이런 깨달음을 얻게 되셨는지도 궁금해요 ㅋㅋㅋ
다른 사람들과는 다른 포인트에서 나는 화가 난다! 고 느끼셨던 걸까요? 굉장히 흥미로운 발견이네요. 🤔

2024-06-11 07:46 UTC, ashsty commented on level2.md
> +그렇게 세운 나의 가설은 "짜증은 욕구 불만족에서 온다."는 것이었다. 사실 이는 가설이라기보단 자명한 사실에 더 가깝다.
이런 점에 대해 가설을 세워보셨다는 점이 정말 재미있는 것 같아요 😆

2024-06-11 07:46 UTC, ashsty commented on level2.md
> +주말에 리뷰가 오지 않아서 정말 실컷 잘 수 있었다. 자고 일어나서 리뷰가 안 온걸 보고 다시 잤다. 덕분에 그동안 지친 심신을 달랠 수 있었다. 이 점에 집중하니까 신기하면서도 당연하게도 짜증이 덜 났다.
진짜 럭키비키네요~ 🍀

2024-06-11 07:46 UTC, ashsty commented on level2.md
> +그럼에도 때로는 논리적인 근거보다 그저 아무 이유 없이 믿는 것이 더 좋을 때도 있지 않을까? 오늘도 더 나은 미래가 있을 것이라 믿고 최선을 다해 살아가는 것이 마음의 여유를 찾는 유일한 방법일 것 같다.
정말 맞는 말 같아요...

똑같은 일이 일어나더라도 그 때 '내'가 어떤 상황에 처해 있고, 어떤 기분이냐에 따라 반응이 완전히 달라지기도 하잖아요. 저도 개인적으로 기분이 태도가 되는 성향이 강하고, 또 그런 점을 조금 억제하려고 노력하는 편인 만큼 로빈의 말에 상당히 공감이 가네요. 

제가 생각하는 '진짜 어른'의 기준은 이래요.

- 어떤 일이 있더라도 기분이 일정 선을 유지할 것
- 설령 그러지 못한 상황이 있더라도 그것이 남들을 대하는 태도가 되지 않도록 노력할 것

저도 잘 지키지 못하는 일이 종종 있지만 🥲
우선은 그런 빈도를 점점 줄여 나가 보려는 시도 중에 있답니다.

로빈도 이런 자그마한 목표들을 몇 가지 세워 보고 작게 작게 체크 리스트를 채워 나가보며 본인의 성장을 체감해보시는 건 어떤가요?

2024-06-11 13:04 UTC, hyxrxn approved these changes
로빈 안녕하세요~~ 잘 아시겠지만 아토입니다~~~
글쓰기 미션에서까지 만나게 되다니... 반갑네요 ㅋㅋㅋㅋ

(스스로 생각하기에) 짜증이 잘 안나는 사람으로서 소재부터 굉장히 흥미롭네요.
글을 읽으며 `짜증`에 대해 이것저것 생각해보았는데요,
제가 예전에 인상깊게 봤던 것 중 [이런 영상](https://www.youtube.com/watch?v=GD5TmEIEK38)이 있습니다!
다음 레벨에서 이런 고민도 함께 해보시면 유연성 강화에 더 도움이 될 것 같아요!

글이 매끄러워서 읽기 좋네요. 잘 읽었습니다!

2024-06-11 15:48 UTC, ChooSeoyeon approved these changes
안녕하세요! 로빈:)
로빈의 솔직한 내면을 글로 풀어내주셔서 재밌게 읽었습니다!

감정을 수치화하는 모습도 인상 깊었고,
새로운 유연성 강화 목표를 도출해내는 과정도 인상 깊었습니다!

로빈의 럭키비키 응원합니다!

2024-06-12 06:47 UTC, robinjoon commented on level2.md
> +그래서 레벨 2에서는 다른 목표를 세워보려고 했다. 레벨 1에서 유연성 강화 목표를 학습이나 우테코 생활 속에서 찾은 것이 아니라 그 밖의 생활에서 찾은 크루도 있었다.
> 앞의 접속사는 없어도 잘 읽힙니다! + 문장을 적절하게 배치해서 가독성이 좋게끔 만들어 보아요!

이 부분은 지금이 더 이해하기가 좋은 것 같아요. 문장의 핵심이 유연성 강화 목표이기 때문에, 그것이 주어가 되는게 좋다고 생각해요

2024-06-12 08:45 UTC, fromitive approved these changes

2024-06-12 08:46 UTC, Largopie approved these changes

2024-06-12 08:47 UTC, donghoony approved these changes

2024-06-13 06:58 UTC, HoeSeong123 commented
안녕하세요 로빈~~ 초롱입니다! 글 정말 잘 읽었어요.

로빈은 개발 실력도 뛰어난 것 같고 그 덕에 우테코 외에도 이것저것 하는 것 같아서 이런 고민을 하고 있는 줄은 몰랐네요.
제가 로빈과 아직 깊은 대화를 나눠보지 않아서 그런지 짜증이 많다는 것도 잘 몰랐었습니다. 부정적인 사고를 자주 한다는 것은 알고 있었지만요.😅

하지만 그만큼 짜증을 엄청 드러내지는 않는다고 생각해요.
기분이 태도가 되지 않는 것은 정말 어려운 일인데 로빈은 잘 해내고 있다고 생각합니다.
물론 제가 모르는 부분이 있기 때문에 다음 목표를 짜증을 드러내지 않기로 잡은 거겠죠? 🤭

로빈을 보면서 항상 '아 나도 저렇게 개발을 좋아하고 싶다' 라는 생각을 하곤 합니다.
전에 영어 스터디 회의를 할 때 로빈이 일상적인 얘기보다 기술적인 얘기를 훨씬 더 많이 한다는 것을 들었을 때는 정말 웃기면서도 대단하다고 생각했습니다.
그래서 저도 뭔가 개발을 좋아하기 위해 미션을 더 열심히 한 적도 많았어요.
그만큼 많은 자극을 받았습니다.

오늘 점심 먹으면서 캠퍼스 찢어지면 연락 안한다 하면서 장난 쳤지만 절대 그럴 일 없습니다.
꾸준히 연락할거고 로빈과 많은 기술적 얘기를 나눠보고 싶어요.
물론 그 전에 제가 기술적 얘기를 나눌 수 있을만한 지식을 쌓아야겠지만요😅

레벨 3 가서도 짜증을 드러내지 않음과 동시에 지금 하고 있는 노력도 꾸준히 했으면 좋겠습니다.
그래서 마음의 여유를 잔뜩 찾았으면 좋겠어요!!
항상 행복하고 긍정적인 하루를 보내길 바랍니다☺️

2024-07-31 02:14 UTC, merged