[레벨 2 글쓰기] 호티(윤주호) 미션 제출합니다.
woowacourse/woowa-writing pull request #227
Opened 2024-06-05 08:19 UTC by Ho-Tea

안녕하세요 백엔드 호티입니다!
레벨 1에서 작성한 글쓰기에 이어서 레벨 2에서 깨달은 것들 위주로 작성하였습니다.
부족한 글쓰기 실력이지만 잘부탁드리겠습니다  🙇‍♂️

[레벨 1 글쓰기](https://github.com/Ho-Tea/woowa-writing/blob/level1/Level1.md)
[레벨 2 글쓰기](https://github.com/Ho-Tea/woowa-writing/blob/level2/Level2.md)

2024-06-06 17:26 UTC, donghoony requested changes
안녕하세요 호티! 1기 선배와의 상담타임에서 잠깐 이야기하게 되었던 아루입니다 😁 글 재미있게 읽었어요. 몇 가지 개선할 수 있을 부분에 코멘트를 남겼습니다. 전반적인 피드백은 이 댓글에서 진행할게요!

- 전반적인 띄어쓰기 / 맞춤법을 [이곳](http://164.125.7.61/speller/)에서 한 번 확인한 뒤 적용해주세요! 
- 조금 어려운 내용일지도 모르겠지만, 글은 문단의 집합이라고 생각해요. 문단은 여러 문장으로 이루어져 있고, 각각의 문단이 서로 줄바꿈으로 마무리돼요. 하나의 이야기는 하나의 문단에서 마무리하는 게 제가 글을 쓸 때 집중하는 부분 중 하나입니다 🙂 <p>[이 글](https://uphuman.tistory.com/5)을 보고 쉼표나 줄넘김이 꼭 필요하지 않은 부분에 들어갔는지도 생각해보면 좋겠습니다! 물론 개인적인 의견이니 괜찮다고 생각되신다면 반영해주세요 😄

유강스 목표도 다른 방향을 바라보고 있어서 흥미로웠어요. 다시 멘션 주시면 추가 코멘트로 찾아뵐게요! 고생하셨습니다 🔥

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +이러한 긍정적인 사고 탓인지 레벨 1이 끝날 즈음에 긍정적인 미래를 꿈꾸며 레벨 2를 기약했다.
'긍정적인'이라는 단어가 반복적으로 등장하니, 다른 유의어를 쓰면 어떨까요?
\+ `긍정`과 `탓`이 서로 어울리지 않는 느낌이 들어요!
```suggestion
이러한 긍정적인 사고 덕분에 레벨 1이 끝날 즈음에 보다 나은 레벨 2를 기약했다. 
```

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +`자기자신`을 긍정적으로 바로볼 수 있는가는 사실 잘 모르겠다 <br>
👀 
```suggestion
`자기자신`을 긍정적으로 바로볼 수 있는가는 사실 잘 모르겠다. <br>
```

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +레벨 2가 시작되고 나서부터는 밀려오는 미션에 대한 압박감과 나만 뒤처지는 것 같은 초조함이 레벨 1과는 비교도 되지 않을 정도로 많아졌다.<br>
`압박감`, `초조함`이라는 단어는 `많다`와 호응이 어색해요. `자주 찾아왔다` 정도가 어울리려나요? 🤔

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +사실 전부터 `나는 자존감이 정말 높은 것일까` 라는 생각을 종종 하곤 했었다. <br>
`했다`와 `했었다`의 차이를 알아보면 좋겠네요! 완전히 단절된 것이 아니라면, `했다`가 더 어울릴지도 모르겠습니다. ([참고](https://ko.dict.naver.com/#/correct/korean/info?seq=5993))

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +우선 할 수 있는 것은 내가 자존감이 정말 높은것인가 회고하게 해준 압박감과 초조함을 이겨내는 것부터 시작하자 <br>
문장 구성 호응을 확인해주세요! `할 수 있는 것`과 `시작하자`가 어색합니다. `우선 할 수 있는 것은 ~~이다`가 조금 더 자연스럽게 느껴져요.

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +그렇게 레벨 2 유연성 강화 목표는 `모르는 키워드나 내용 공부를 미루지 않는 것`으로 정하였다.
제 목표와 완전 상반되는데요? 저는 깊은 공부는 미션 끝나고 하는 것으로 잡아 두었습니다 🥹

2024-06-06 17:26 UTC, donghoony commented on Level2.md
> +우아한 테크 코스를 통해 내 자존감이 무너졌지만, 그 자존감은 진정한 자존감이 아니었음을 깨달았다.
`우아한테크코스`는 고유명사라 붙여 씁니다!

2024-06-07 06:25 UTC, sh1mj1 reviewed
특별한 경험을 통해 자존감에 대해 깊게 생각하게 되었군요!
그리고 우선 할 수 있는 부분에 대한 목표를 세우고, 실천하기를 마음 먹은 과정이 인상 깊네요!

글의 서론에서는 자존감에 대한 이야기가 길어서, 글이 자존감에 대한 이야기가 될 줄 알았는데,
본론과 결론이 그렇지 않았네요.
자존감에 대한 생각보다, 우선 할 수 있는 것부터 하자는 내용이 핵심 메시지인 것 같아요.

제가 이해한 내용이 맞을까요?
만약 그렇다면 핵심 메시지보다 서론이 너무 길다는 생각이 들기도 합니다.

물론 제가 글을 잘 읽는 사람이 아니라서 그렇게 받아들였을 수도 있어요!
이에 대해서 호티의 생각이 궁금합니당

2024-06-07 06:25 UTC, sh1mj1 commented on Level2.md
> +그것이 `자기자신`을 긍정적으로 바라 볼 수 있는 것과 `자신`을 사랑하는 감정을 가지고 있는 것과는 다르다고 생각된다.
바라볼 수 있는 것과, 가지고 있는 것
이렇게 `~수 있다` 표현을 쓸 필요가 있을까요?

그리고 `생각된다` 라는 수동 형태의 서술어를 쓸 필요가 있을까요?
의도에 따라서 `생각한다`라는 표현도 없앨 수 있을 것 같아요.

저는 개인적으로 아래처럼 쓸 것 같아요.
```suggestion
'자기자신`을 긍정적으로 바라보는 것과 `자신`을 사랑하는 것은 다르다.
```

2024-06-07 06:25 UTC, sh1mj1 commented on Level2.md
> +하지만 그러한 압박감과 초조함은 나를 항상 긴장 상태로 만들며, `내가 잘할 수 있을까?` 하는 의심과 함께 자신감을 줄어들게 했고, 자존감을 깎아내리기 시작했다. <br>
한 문장에 너무 많은 정보가 있는 것 같아요.
여러 문장으로 나눌 수 있지 않을까요?

2024-06-07 06:25 UTC, sh1mj1 commented on Level2.md
> +틀린 말이 하나 없었다, 들으면 들을수록 내 속을 훤히 꿰뚫어 보는 것만 같았다.<br>
가장 간단히 자신의 감정을 표현하고,
그에 대해 더 구체적인 부연 설명을 다음 문장에 붙여주셨네요.
이 부분은 정말 속도감 있게 잘 읽혔습니다!

2024-06-09 04:56 UTC, Mingyum-Kim reviewed
안녕하세요 호티 ! 
글쓰기 미션 리뷰어 안나입니다 😃

자존감이 스스로 높다고 생각하였는데 다소 충격적인 (?) 사건을 통해 생각을 바꾼 후 실천을 통해 극복해나가는 과정이 글에서 잘 보여져요. 늘 `너무 좋아` `너무 재밌어`를 외치는 호티라 당연히 긍정적이고 자존감이 높다고 생각했는데, 내면에서는 여러 가지 시행착오가 있었군요 😮 

이해가 잘 안되는 부분에 대해서 리뷰 달아놓았습니다. :) 다음 글에서는 스스로의 모습에서 자존감을 찾고 긍정적인 모습을 유지하는 호티의 모습 기대해보겠습니다~

2024-06-09 04:56 UTC, Mingyum-Kim commented on Level2.md
> +자존감이 높은 사람이라면 이러한 감정들이 들 때에 자기 자신을 긍정적으로 바라보면서, 감정들을 촉진제로 사용해 자신을 발전해 나가려 하지 않을까
`감정들을 촉진제로 사용한다`라는 맥락이 이전에는 등장하지 않았던 부분이라 새롭게 느껴지네요.
글을 읽으면서 **자존감이 높다 = 남이 아닌 내가 나를 인정해주는 것**이라고 이해하였는데, **감정을 촉진제로 사용한다는 것 또한 자존감이 높은 사람의 특징이다.** 라는 것은 어떤 경험이나 생각을 통해 얻은 교훈인 지 궁금해요.

2024-06-09 04:56 UTC, Mingyum-Kim commented on Level2.md
> +우선 할 수 있는 것은 내가 자존감이 정말 높은것인가 회고하게 해준 압박감과 초조함을 이겨내는 것부터 시작하자 <br>
이 인용 구문은 어디에서 사용된 것인가요? 아니면 호티가 했던 생각을 쓴 것일까요? 😃
레벨 2 유연성 강화 목표와 어떤 연관이 있는 건지 한번에 와닿지 않는 것 같아요!

2024-06-09 06:24 UTC, 0jenn0 commented
안녕하세요 호티 FE 리버입니다
공감가는 부분도있고 비슷한 경험도 적혀있어서 재밌게 잘 읽었습니다
피드백 몇 자 적고 가겠습니다
레벨2도 열심히 달리시느라 고생하셨습니다 ~

2024-06-09 06:32 UTC, 0jenn0 commented on Level2.md
> +한번은 리뷰어로 활동 중이신 1기 선배님이 루터회관을 찾아왔을 때였다.<br>
글쓰기 피드백을 위해 여러 글을 읽었는데, 많은 크루가 상담을 통해 많은 것을 배우는것 같네요
(저 또한 그랬습니다)

2024-06-09 06:32 UTC, 0jenn0 commented on Level2.md
> +벌거벗겨진 기분이었다. <br>
저도 상담 시간에 이런 경험을 해서 공감가네요

2024-06-09 06:32 UTC, 0jenn0 commented on Level2.md
> +그러면 내 자신을 사랑하는 것은 어떻게 해야 할까 <br>
일단 저는 제가 저 자신에게 실망할만한 행동을 했을 때 질책하지 않고 `괜찮아 그럴수도있지` 라고 생각하기부터 시작 중입니다.
그 대신 저 생각만으로 끝나는게 아니라 개선하기위한 액션플랜 생각을 바로 생각해보려하고있어요

2024-06-10 12:56 UTC, le2sky requested changes
호티 안녕하세요. 아톰입니다.
자신의 모습을 되돌아보면서, 성장하는 내용이 담긴 멋진 글이네요.
사소한 코멘트 하나 남겼으니, 시간 나시면 확인 부탁드려요.
남은 레벨 2 기간도 응원합니다. 😀

2024-06-10 12:56 UTC, le2sky commented on Level2.md
> +그러한 긍정적인 사고 탓인지 레벨 1에서의 유연성 강화 목표도 어느 정도 이뤄낸 것 같다. <br>
위에 나오는 문장과 비슷해보는데, 의도하신걸까요?! 그렇다면, 아루의 피드백을 반영하실 때 이 부분도 함께 신경 써주시면 좋을 것 같아요.

2024-06-10 12:56 UTC, le2sky commented on Level2.md
> +예를 들어 `가려던 카페가 만석이라면 이 기회에 다른 카페를 가보는 것도 괜찮겠다`, <br>
파스쿠찌인가요? 궁금하네요. 👀

2024-06-11 12:30 UTC, ksk0605 reviewed
호티의 자존감에 대한 이야기 흥미롭게 잘 들었어요!
극복하기 위한 노력도 함께 작성되어있어서 더 좋았네요 ㅎㅎ
호티의 진짜 자존감 찾아가기! 기대할게요 😀

2024-06-11 12:30 UTC, ksk0605 commented on Level2.md
> +평소에 무엇이든지 긍정적으로 사고하려고 노력하곤 한다 <br>
```suggestion
평소에 무엇이든지 긍정적으로 사고하려고 노력하곤 한다. <br>
```
매의 눈👀

2024-06-11 12:30 UTC, ksk0605 commented on Level2.md
> +이러한 긍정적인 사고 탓인지 레벨 1이 끝날 즈음에 긍정적인 미래를 꿈꾸며 레벨 2를 기약했다.
```suggestion
이러한 긍정적인 사고 덕분인지 레벨 1이 끝나기도 전에 긍정적인 미래를 꿈꾸며 레벨 2를 기약했다. 
```
저는 의미가 더 잘 드러나도록 위처럼 수정해보는 것도 좋아보여용 😀

2024-06-11 12:30 UTC, ksk0605 commented on Level2.md
> +레벨 2가 마무리 되어가고 있는 이 시점에는 `내가 틀렸을 수도 있다`는 사고가 기반에 깔리게 되어
여러 의미를 지닌 문장은 쪼개도 좋을 것 같아요!

2024-06-11 12:30 UTC, ksk0605 commented on Level2.md
> +한번은 리뷰어로 활동 중이신 1기 선배님이 루터회관을 찾아왔을 때였다.<br>
```suggestion
한번은 리뷰어로 활동 중이신 1기 선배님이 루터회관을 찾아오신 적이 있다.<br>
```
가 더 자연스러운 문장인 것 같아요!

2024-06-11 12:30 UTC, ksk0605 commented on Level2.md
> +이러한 사고를 통해 나를 흔들리게 했던 것들을 하나씩 타파하다 보면
```suggestion
나를 흔들리게 했던 것들을 하나씩 타파하다 보면
```
없어도 크게 어색하지 않은 것 같아요!

2024-06-12 02:26 UTC, Ho-Tea commented on Level2.md
> +오히려 좋다는 말을 입에 달고 산다.
첨부해주신 [링크](https://uphuman.tistory.com/5) 잘 보았습니다!
평소 줄바꿈을 통해 독자에게 말을 건네는 방식으로 글을 풀어 나갔지만, 
하나의 문단에서 말하고자 하는 것을 이야기 해보는 것으로 반영했습니다 👍

2024-06-12 02:40 UTC, Ho-Tea commented on Level2.md
> +사실 전부터 `나는 자존감이 정말 높은 것일까` 라는 생각을 종종 하곤 했었다. <br>
세심한 피드백 감사드립니다..👍👍

2024-06-12 03:34 UTC, Ho-Tea commented on Level2.md
> +우선 할 수 있는 것은 내가 자존감이 정말 높은것인가 회고하게 해준 압박감과 초조함을 이겨내는 것부터 시작하자 <br>
말씀해주신 문장 구성 호응을 생각해 아래와 같이 수정해 보았습니다!
`우선 내가 자존감이 정말 높은것인가 회고하게 해준 압박감과 초조함을 이겨내는 것부터 시작하자.`

2024-06-12 03:59 UTC, 0jenn0 commented
안녕하세요 호티
제가 피드백보다는 감상문에 가깝게 남겨서 미리 approve 하겠습니다
레벨3도 같이 힘내보아요!!

2024-06-12 04:01 UTC, 0jenn0 approved these changes
안녕하세요 호티
제가 피드백보다는 감상문에 가깝게 남겨서 미리 approve 하겠습니다
레벨3도 같이 힘내보아요!! 💪

2024-06-12 04:01 UTC, Ho-Tea commented on Level2.md
> +그렇게 레벨 2 유연성 강화 목표는 `모르는 키워드나 내용 공부를 미루지 않는 것`으로 정하였다.
아루의 글에서 `공과 사를 구분하라`라는 구절이 굉장히 인상깊었어서 기억합니다 👍
저도 깊은 공부는 미션 끝나고 진행하려고 생각했으나, 그 깊은 공부의 기준이 저에게는 되게 모호하게 다가오더라구요..ㅠ
그래서 우선은 생각나는 것들을 정리하고자 목표를 저렇게 설정했던 것 같아요!

2024-06-12 04:05 UTC, Ho-Tea commented on Level2.md
> +그것이 `자기자신`을 긍정적으로 바라 볼 수 있는 것과 `자신`을 사랑하는 감정을 가지고 있는 것과는 다르다고 생각된다.
꼼꼼한 피드백 감사드립니다 🙇‍♂️
제안해주신 문장이 더 간결하며, 제 생각을 강조하는 것 같아 좋은 것 같아요!
반영하였습니다

2024-06-12 04:27 UTC, Ho-Tea commented on Level2.md
> +자존감이 높은 사람이라면 이러한 감정들이 들 때에 자기 자신을 긍정적으로 바라보면서, 감정들을 촉진제로 사용해 자신을 발전해 나가려 하지 않을까
자존감이 높은 사람도 앞서 말한 불안, 초조와 같은 감정을 느낄 것이라 생각되었고, 
자존감이 낮은 사람은 그러한 감정이 다가왔을 때 그 감정에 무너지지만 자존감이 높은 사람은 오히려 그러한 감정을 이용해 
자신을 성장, 발전해 나가려 하지 않을까 생각했습니다 🤔

2024-06-12 04:35 UTC, Ho-Tea commented on Level2.md
> +우선 할 수 있는 것은 내가 자존감이 정말 높은것인가 회고하게 해준 압박감과 초조함을 이겨내는 것부터 시작하자 <br>
의식의 흐름대로 생각한 내용을 투박하게 적어낸 부분이였습니다!
압박감과 초조함이 현재는 학습으로부터 촉발되었다 생각해 해당 감정을 이겨내기 위해
유연성 강화목표를 학습과 관련한 `모르는 키워드나 내용 공부를 미루지 않는 것`로 설정하게 되었습니다!

2024-06-12 04:38 UTC, Ho-Tea commented on Level2.md
> +그러면 내 자신을 사랑하는 것은 어떻게 해야 할까 <br>
좋은 방향성을 얘기해주셔서 감사합니다 😊
생각으로만 멈추지 않고 실천하여, 개선하려는 시도가 좋은 것 같습니다
저도 해보겠습니다!!

2024-06-12 04:40 UTC, Ho-Tea commented on Level2.md
> +예를 들어 `가려던 카페가 만석이라면 이 기회에 다른 카페를 가보는 것도 괜찮겠다`, <br>
파스쿠찌에서도 이러한 경험이 있기는 합니다..👀

2024-06-12 06:21 UTC, Ho-Tea commented on Level2.md
> +한번은 리뷰어로 활동 중이신 1기 선배님이 루터회관을 찾아왔을 때였다.<br>
아래와 같이 수정해 보았습니다!
`한번은 리뷰어로 활동 중이신 1기 선배님이 루터회관을 찾아오셨을 때의 일이다.`

2024-06-12 06:34 UTC, donghoony approved these changes
안녕하세요 호티! 피드백 반영한 거 확인했습니다. 보다 읽기 수월해졌네요 🔥

길지는 않았지만 저 또한 안돌과 함께 이야기를 하면서 많은 것을 배우게 되었네요. 내가 아는 나와, 다른 사람이 나를 바라보는 내가 얼마나 다른지를 체감할 수 있었던 시간이라고 생각합니다.

레벨 3부터는 꾸준히 프로젝트를 함께할 다른 크루들과 함께하게 될 텐데, 좋은 에너지가 될 것이라는 게 벌써 보이네요 🥹 앞으로도 잘 달려보자고요! 수고 많으셨습니다 🙂

2024-06-12 10:16 UTC, le2sky approved these changes
호티 고생 많으셨어요. 
방학 푹 쉬시고 레벨 3때 만나요. 😀

2024-06-12 11:10 UTC, Mingyum-Kim approved these changes
안녕하세요 호티 🐯
글에 대해 상세히 설명해줘서 생각의 배경을 이해하는 데 도움이 많이 되었습니다 ~ 
Approve 남기고 갈게요 ㅎㅎ 글쓰기 미션 수고하셨습니다 !!

2024-06-12 12:46 UTC, ksk0605 approved these changes
고생많으셨어요 호티!!! 
글이 많이 다듬어졌네요👍👍

방학 맛있게 즐기세요!!

2024-06-12 13:06 UTC, sh1mj1 approved these changes
우테코 선배 기수 분과의 경험이 현장감 있게 잘 느껴졌던 글이었던 것 같아요!
잘 읽었습니다!
lv 2 고생 많으셨습니다!!

2024-07-31 02:15 UTC, merged