[레벨 2 글쓰기 미션] 리니(이예린) 미션 제출합니다.
woowacourse/woowa-writing pull request #236
Opened 2024-06-05 09:18 UTC by linirini

미션 제출합니다.

2024-06-06 15:27 UTC, reddevilmidzy requested changes
리니 글 잘 읽었어!! 

스터디 때 작성했던 글을 공유하는 독특한 형태여서 좀 더 친근하게 다가오는 느낌이였어 🥰

2024-06-06 15:27 UTC, reddevilmidzy commented on level2.md
> +그랬는지 이때 이후로는 전보다 더 늘어져 있을 때가 많았다.<p>
문장 시작을 `그랬는지`로 하는게 약간 어색한거 같아요

`그래서인지`로 시작하는건 어떤가요?

2024-06-06 15:27 UTC, reddevilmidzy commented on level2.md
> +하지만 **최선**을 다하고 있다는 생각은 들지 않았다.<br>
위에서 `열심히` 학습했다고 하는데 아래서 `최선`을 다하고 있다는 생각은 들지 않는다고 하는데, 제 개인적인 생각으로는 열심히 하는게 최선을 다하는거 같아요 😂

"~께서"나 "~해 주시는"과 같이 리뷰어 이야기를 쓸 때 존칭을 사용하고 있는데, 사용하지 않는것이 좀 더 자연스러운거 같기도 하고 


저 같으면 이렇게 작성할 거 같아요! 

`리뷰어가 던져주는 키워드에 대해서 학습하고, 피드백을 반영하면서도 **최선**을 다하고 있다는 생각은 들지 않았다.`

2024-06-06 15:27 UTC, reddevilmidzy commented on level2.md
> +레벨 2에 와서는 소속감이 주는 안정감 때문인지, 초심 에너지를 잃은 탓인지 많이 해이해졌다.
`초심 에너지를 잃은` 보다 그냥 `초심을 잃은`도 괜찮은거 같은데 취향차이일수도...? 🤗

2024-06-10 05:00 UTC, hw0603 reviewed
다른 크루들이 이미 수정사항들을 잘 달아 주셔서 제가 리뷰 드릴 부분이 많지는 않네요! 글 잘 읽고 갑니다😀

2024-06-10 05:00 UTC, hw0603 commented on level2.md
> +#### 레벨 2 글쓰기 : 유연성 강화 스터디에서 쓸 내용이 없다! 글쓰기에 쓸 내용이 없다!
😂

2024-06-10 05:00 UTC, hw0603 commented on level2.md
> +테코톡 주제로 내가 잘 모르는 개념을 정했고, 그렇다 보니 예전의 나처럼 부족함밖에 보이지 않는 상태로 테코톡을 준비했다.<p>
그렇다기엔 발표 엄청 잘 하시던걸요👍

2024-06-10 05:00 UTC, hw0603 commented on level2.md
> +글에서 많이 등장하는 단어는 "아쉬운", "못했다"이다.
문장에서 단어를 강조할 때는 큰따옴표 대신 작은따옴표 `'`를 사용하는 건 어떨까요?

2024-06-10 05:00 UTC, hw0603 commented on level2.md
> +그렇다면, 지금은 관대해지기보다는 엄격해져야 하는 순간이지 않을까?<br>
익숙함과 편안함에서 오는 안정감이 성장속도를 늦출 때가 분명히 있죠. 항상 경계해야 할 부분인 것 같아요. 최근에 저도 조금 늘어지는 듯한 느낌을 받았는데 글 읽고 마음 한 번 다시 잡고 갑니다ㅎㅎ

2024-06-10 11:10 UTC, ikjo39 reviewed
안녕하세요 리니!
레벨 2에 번아웃이 왔던 크루 중 하나로서 리니의 관대함에 대해 공감하며 읽었어요.
저도 변화하려는 인간은 본래의 모습으로 돌아오기 쉽다는 의견인데요.
이에 대해 두 가지 행동 지침을 들어 공유하고 싶어요.
- 의도적으로 주변 환경을 만든다. (ex. 책을 주변 곳곳에 두어 5분이라도 본다.)
- 할일을 잘게 쪼개어 하나씩 달성해가며 성취감을 얻는다. (이때, 이전 과정으로 돌아오지 않도록 완벽하게 해낸다.)

저 또한 변화해가는 과정에 있기에 리니의 다음 레벨 유강스 목표를 응원할게요!! :

2024-06-11 01:56 UTC, J-I-H-O approved these changes
리니 안녕하세요! 땡이입니다 😊👍
글 재미있게 잘 읽었어요. 간단하게 의견 남겨보았는데, 선택적으로 반영해주시면 좋을 것 같습니다!
리니의 성장을 응원합니다!

2024-06-11 01:56 UTC, J-I-H-O commented on level2.md
> +레벨 2에 와서는 소속감이 주는 안정감 때문인지, 초심 에너지를 잃은 탓인지 많이 해이해졌다.
`초심을 잃은` 또는 `에너지를 잃은` 이 더 자연스러운 것 같아요!

2024-06-11 01:56 UTC, J-I-H-O commented on level2.md
> +이 당시에 테코톡에만 집중하느라 테코톡이 끝난 후에도 못 했던 과제까지 하기 위해서는 평일과 주말 구분 없이 캠퍼스에서 온종일 있어야 했다.
```suggestion
이 당시에 테코톡에만 집중하느라 과제에 집중하지 못했다. 밀린 과제까지 처리하기 위해서는 평일과 주말 구분 없이 캠퍼스에서 온종일 있어야 했다.
```

문장을 끊어주는 것이 읽기에 더 수월할 것 같아요!
위 문장은 예시일 뿐이니 취향에 따라 바꿔봐도 좋을 것 같습니다!

2024-06-11 01:56 UTC, J-I-H-O commented on level2.md
> +이 목표를 설정할 당시에는 소속된 곳이 없어서 안정감이 없이 조급한 상태였다. 더불어 본래 나의 부족함에 집중하던 습관 때문에 자신감도 떨어져 있었다.<br>
```suggestion
이 목표를 설정할 당시에는 소속된 곳이 없어 안정감 없이 조급한 상태였다. 더불어 본래 나의 부족함에 집중하던 습관 때문에 자신감도 떨어져 있었다.<br>
```
좀 더 간결하게 표현할 수 있을 것 같습니다!

2024-06-11 01:56 UTC, J-I-H-O commented on level2.md
> +그래서 레벨 3에서는 기존의 목표를 유지하더라도, 유연하게 대처하는 연습을 해보려고 한다.
리니의 성장을 응원합니다! 화이팅! 🔥

2024-06-11 02:52 UTC, hw0603 approved these changes

2024-06-11 12:39 UTC, linirini commented on level2.md
> +하지만 **최선**을 다하고 있다는 생각은 들지 않았다.<br>
덕분에 문장이 깔끔해졌습니다, 고마워요👍

2024-06-11 12:46 UTC, linirini commented on level2.md
> +그렇다면, 지금은 관대해지기보다는 엄격해져야 하는 순간이지 않을까?<br>
레벨 2 막바지에 오면서 비슷한 느낌을 받는 크루들이 정말 많은 것 같아요.! 레벨 2 잘 마무리하고, 방학 잘 쉬고, 레벨 3 열심히 달려봐요:)

2024-06-11 12:47 UTC, linirini commented on level2.md
> +테코톡 주제로 내가 잘 모르는 개념을 정했고, 그렇다 보니 예전의 나처럼 부족함밖에 보이지 않는 상태로 테코톡을 준비했다.<p>
걱정이 정말 많았었는데, 그렇게 말해줘서 고마워요:)

2024-06-11 12:49 UTC, linirini commented on level2.md
> +그랬는지 이때 이후로는 전보다 더 늘어져 있을 때가 많았다.<p>
페어 프로그래밍과 테코톡이 겹치다니... 정말 쉽지 않았겠어요😭

2024-06-11 12:51 UTC, linirini commented on level2.md
> +이 당시에 테코톡에만 집중하느라 테코톡이 끝난 후에도 못 했던 과제까지 하기 위해서는 평일과 주말 구분 없이 캠퍼스에서 온종일 있어야 했다.
문장이 더 간단명료해졌어요, 고맙습니다👍

2024-06-12 02:18 UTC, ikjo39 approved these changes
굿굿 고생했어요 리니~

2024-06-12 03:30 UTC, reddevilmidzy approved these changes
리니 글 잘읽었어!!
레벨 2 수고 많았고, 레벨 3도 같이 힘내보자!! 💪

ps) 요상한 xml 파일도 같이 올라간거 같은데 지워도 될거 같아! 

![image](https://github.com/woowacourse/woowa-writing/assets/78539407/445af9a6-2f03-4354-aef4-5a29ebb3eba1)

2024-06-12 04:57 UTC, chysis approved these changes
안녕하세요 리니! 피드백 반영해주신 것 확인했어요 :)
글이 잘 다듬어진 것 같아요. 
레벨 2 동안 고생 많으셨습니다!! 😊👍

2024-07-31 02:15 UTC, merged