[레벨 2 글쓰기 미션] 종이(최우종) 미션 제출합니다.
woowacourse/woowa-writing pull request #256
Opened 2024-06-05 12:46 UTC by dwax1324

안녕하세요 백엔드 종이입니다.😄

아직 글이 미완성이지만 유연성을 발휘해 제출합니다.

곧 리펙터링 하겠습니다 잘부탁드립니다!

2024-06-07 12:03 UTC, jinhokim98 requested changes
안녕하세요 종이! 리뷰를 맡은 프론트엔드 쿠키입니다!
글이 미완성인 것 같아서 일단은 RC 드릴게요! 나중에 글 수정하시고 알려주시면 리뷰 하러 오겠습니다 :)

2024-06-07 12:03 UTC, jinhokim98 commented on level2.md
> +�۾��� �̼��� �� ���� �ʽ����� ���ư��� �� ����. ���� �̼��� ���� ���鼭 ���� �󸶳� ���峪 �־����� �˰� �Ǿ���. �������ũ�ڽ��� ���� ���� ���� ������, �����ڽ��� �ϸ鼭 4,000�ھ� ä���� �Ұ���, �����ڵ��׽�Ʈ�� �غ��ϸ� �޾���
글쓰기 미션을 할 ??면 (글씨가 깨져서보여요ㅜㅜ)
![image](https://github.com/woowacourse/woowa-writing/assets/81083461/29cf3acb-8d9c-40f1-ad81-07e86030edb5)

2024-06-09 11:39 UTC, unifolio0 approved these changes
우테코 초반의 종이 모습과 많이 달라졌다고 매번 느끼는데 그 과정을 조금이나마 엿볼 수 있는 글이었어요. 글로 읽어도 많은 감동을 느꼈지만 나중에 직접 말로도 듣고 싶네요. 레벨 2 정말 수고 많았어요.

글 잘 읽고 갑니다!

2024-06-09 11:39 UTC, unifolio0 commented on level2.md
> +글쓰기 미션에서만큼은 솔직해지고 싶다. 이번에는 정말 달라지고 싶었다. 인생의 마지막 갈림길에서까지 도망치기 싫었다. 말 한마디 못했지만 회식에도 참여해보고, 용기 내어 코치와의 면담도 해봤다. 하지만 아무리 발버둥쳐도 나사가 헛도는듯한 느낌이었다. 다른 사람들은 모두 물 속에서 헤엄치고 있는데 나만 밖에서 관망하고 있는 느낌이었다. 같은 공간 속에서 다
`인생의 마지막 갈림길에서까지 도망치기 싫었다.`에서 종이가 말하는 인생의 마지막 갈림길은 무엇을 말하는 건가요? 이번 글쓰기 미션? 우테코?

2024-06-09 11:50 UTC, Mingyum-Kim reviewed
종이 ~
명작을 그냥 지나칠 수 없어서 흔적을 남기고 갑니다.

종이 글을 읽으면 마음이 따뜻해지는 기분이 들어요 😄 수려하지 않지만 강렬하고 풍성한 표현력과 종이 스스로의 내면에 대한 통찰력이 어우러져서 좋은 글이 나온 것 같아요. 그냥 작가로 데뷔해주시면 제가 너무 즐거울 것 같은데요 ㅋㅋ 앞으로도 종이의 성장하는 모습 옆에서 지켜보겠습니다. 💪💪

2024-06-09 11:50 UTC, Mingyum-Kim commented on level2.md
> +> 정체불명의 독화살을 맞은 사람이 매우 괴로워하고 있다. 이를 본 행인이 화살을 뽑아주려 했지만 그는 "화살을 뽑지 마라. 누가 쏜 것인지 먼저 알아야겠다."라며 치료를 거부했다. 또, "어떤 독이고, 화살의 재질은 무엇으로 이루어져 있는지, 어느 방향에서 날라온 것인지 먼저 알아야겠다."라며 당장 답할 수 없는 질문만 되풀이하고 치료를 거부하다가 고통
이 인용 구문은 어디서 가져온 글인가요? 궁금합니다 😃  아니면 종이가 지어낸 글인건가요?

2024-06-09 11:50 UTC, Mingyum-Kim commented on level2.md
> +이젠 고민의 방향을 내부로 쏟아야함을 깨달았다. 그 동안 무시해왔던 내 감정의 변화에 귀기울이고, 과거에 대한 후회와 미래에 대한 걱정을 멈추고, 알아차림을 알아차리면서 나 자신에 대한 탐구를 하고 있다. 그리고 가장 중요한건, 삐뚤빼뚤 모난 나의 모습 그대로를 사랑하기로 했다. 이제 크루들한테 조금씩 장난도 칠 수 있다. 우아한테크코스에서 가장 얻어가고
그냥 여담인데 요즘 굿샷에서 유독 그런 이야기가 많이 들리는 것 같아요. 

"종이가 나한테 요즘 장난을 많이 쳐. 왜인지 모르겠는데 기분이 좋다?" 

종이가 다른 사람들의 마음을 읽을 수는 없겠지만 적어도 다들 종이의 성장을 느끼고 기뻐하고 있는 것 같았어요. 종이의 관심을 받고 있음에 뿌듯해하는 것 같기도 하고요. 😄
사소한 행동으로 누군가에게 즐거움을 주는 종이의 능력이 아닐까 생각이 드네요 ~

2024-06-10 14:56 UTC, jinhokim98 approved these changes
안녕하세요! FE 쿠키입니다.
글을 수정하신 것 같아서 리뷰 드리러왔어요. 글 솜씨도 좋으시고 인용을 정말 잘 하시는 것 같아요!
충분히 잘 쓰신 글 같아서 Approve 드립니다.
내일 중으로 제 글도 리뷰 부탁드릴게요 종이!

2024-06-10 14:56 UTC, jinhokim98 commented on level2.md
> +> 자신을 대단치 않은 인간이라 폄하해서는 안 된다. 그 같은 자신의 행동과 사고를 옭아매려 들기 때문이다. 오히려 맨 먼저 자신을 존경하는 것부터 시작하라. 아직 아무것도 하지 않은 자신을, 아직 아무런 실적도 이루지 못한 자신을 인간으로 존경하는 것이다. 자신의 인생을 완성시키기 위해 가장 먼저 스스로를 존경하라.
맞아요 정말 중요한 내용입니다.
그리고 추가로 스스로를 존경하면서 스스로를 사랑하고 보듬어주는 것도 어떨까요?

2024-06-10 14:56 UTC, jinhokim98 commented on level2.md
> +레벨1을 돌이켜보면 굉장히 힘들었다. 캡틴 포비가 얘기한 '초반에는 적응을 잘 못하다가 좋아지는 크루를 보면 가장 뿌듯하죠'의 그 크루가 되길 바라면서, 송재하 CTO가 얘기한 '다이아몬드가 되기 위해서는 엄청난 압력과 하중을 견뎌야한다'의 그 다이아몬드가 되길 바랐다. 군대를 제외한 8년 동안 혼자 방 안에서 지내다가, '정지 관성'을 이겨내고 잠실캠퍼
어떤 생각에서 그런 생각이 들었는지는 잘 모르지만
하나 해드리고 싶은 이야기가 있는데 대부분의 사람들은 남들에게 그렇게 관심이 없다는거에요. 그래서 무엇인가를 실수해도 잘 기억 못하는 경우가 많죠. 그러니깐 살면서 너무 남을 의식하지 않아도 괜찮아요!

2024-06-10 14:56 UTC, jinhokim98 commented on level2.md
> +나는 이미 태어났는데 태어남의 이유를 오랫동안 갈구하고 있었다. 얼마나 어리석은가? 독화살에 맞아 죽어가고 있는데 치료는 하지 않고 화살에 맞은 이유를 찾고 있었다. 질문 자체는 의미가 있고 도움이 되겠지만, 그 것에 매몰된다면 삶의 이유를 찾기 위해 삶을 단축시키는 아이러니한 상황이 펼쳐진다. 우아한테크코스에 입과하기전에 독화살을 뽑아 냈지만, 오랜 무
우테코에 오기 전 독화살을 뽑아낸 계기에 대해 내용이 보충되도 좋을 것 같아요!

2024-06-10 14:56 UTC, jinhokim98 commented on level2.md
> +이젠 고민의 방향을 내부로 쏟아야함을 깨달았다. 그 동안 무시해왔던 내 감정의 변화에 귀기울이고, 과거에 대한 후회와 미래에 대한 걱정을 멈추고, 알아차림을 알아차리면서 나 자신에 대한 탐구를 하고 있다. 그리고 가장 중요한건, 삐뚤빼뚤 모난 나의 모습 그대로를 사랑하기로 했다. 이제 크루들한테 조금씩 장난도 칠 수 있다. 우아한테크코스에서 가장 얻어가고
다행이네요😄 크루들과 함께하면서 나아지고 있는 종이의 모습이 보기 좋아요!

2024-06-10 14:56 UTC, jinhokim98 commented on level2.md
> +주변에 성장통을 겪고 있는 크루들이 많다. 나도 그렇다. 매일 높은 곳을 올라가기 위해 한 발 한 발 내딛는다. 고개를 떨구면 지나온 길이 짧아 보여 한 숨만 나오고, 고개를 들면 갈 길이 아득히 멀어보인다. 그러나 고개를 들 필요도 내릴 필요도 없다. 지금 당장 해야할 것에 집중하자. 목표를 향해 한 발 한 발 내딛지 않아도 좋다. 잠시 멈춰서서 산수유
이 말 너무 좋네요! 잠시 멈춰서서 이 순간을 즐긴다.
앞으로 나아갈 길은 험하고 많지만 이 순간을 즐기면서 한 발 한 발 내딛는 종이를 응원할게요!

2024-06-11 02:00 UTC, 00kang reviewed
종이 안녕하세요~ FE 초코🍫입니다. 글 잘 읽었습니다 :>

글쓰기 미션을 통해 처음 만났지만, 글을 통해 종이를 알 수 있어 좋았습니다.
앞으로도 겪을 성장통을 어떻게 이겨내실지 궁금해지네요 화이팅입니다!

2024-06-11 02:01 UTC, 00kang approved these changes

2024-06-11 02:05 UTC, eun-byeol approved these changes
종이 안녕하세요! BE 조조입니다.
글 잘 읽었어요. 시적인 글을 굉장히 잘 쓰시네요! 종이의 방식대로 솔직하게 담아주셔서 제가 리뷰 드릴 것은 없을 것 같아요.

> 하지만 아무리 발버둥쳐도 나사가 헛도는듯한 느낌이었다. 다른 사람들은 모두 물 속에서 헤엄치고 있는데 나만 밖에서 관망하고 있는 느낌이었다. 같은 공간 속에서 다른 크루들과의 이질감이 느껴졌다.

저도 느꼈었던 적이 있었어요. 저는 그렇게 외향적이지도 재미있지도 않거든요. 제가 그런 사람이 아닌데 억지로 꾸며내려고 했었다고 해야 할까요..? 제가 너무 지쳐버려서 그 후로는 솔직하게 행동하게 됐어요. `삐뚤빼뚤 모난 나의 모습 그대로를 사랑하기로 했다.` 종이가 말한 그대로요. 그랬더니 저 모습 그대로를 받아줄 수 있는 친구들이 생기기도 하고 마음도 편해졌던 것 같아요. 나만 이런 생각을 한 게 아니구나. 그런 얘기를 해드리고 싶었어요.
이미 종이는 성장통을 잘 이겨내고 계신 것 같아요. 앞으로 남은 우테코 생활도 종이의 방식대로 잘 만들어가시길 응원하겠습니다!🙌

2024-06-11 05:23 UTC, xogns1514 approved these changes
안녕하세요 종이📄 러쉬입니다~
거친 문장 속에서 종이의 감정과 의식이 잘 드러나는 글이었습니다.
글을 통해 그동안의 감정과 고민들을 잘 표현하시는 것 같아요.
제가 지켜봐온 크루들 중 가장 큰 변화가 느껴지는 크루 중 하나가 종이가 아닌가 싶은데요.
종이도 스스로의 변화를 잘 느끼고 있는거 같아서 뿌듯합니다.
그대로의 모습을 사랑하면서 발전하는 길에 응원 한가득 뿌립니다

2024-06-11 05:23 UTC, xogns1514 commented on level2.md
> +이젠 고민의 방향을 내부로 쏟아야함을 깨달았다. 그 동안 무시해왔던 내 감정의 변화에 귀기울이고, 과거에 대한 후회와 미래에 대한 걱정을 멈추고, 알아차림을 알아차리면서 나 자신에 대한 탐구를 하고 있다. 그리고 가장 중요한건, 삐뚤빼뚤 모난 나의 모습 그대로를 사랑하기로 했다. 이제 크루들한테 조금씩 장난도 칠 수 있다. 우아한테크코스에서 가장 얻어가고
글을 읽으면서 가장 기쁜 구간이네요.
레벨 1 부터 지켜보던 크루의 입장에서, 종이가 인간적인 성장을 하고 있다는 것을 느끼고 있습니다. 
스스로를 사랑하는 일은 어쩌면 쉬운 일이지만, 한편으로는 정말 어렵기도 한 것 같습니다. 
종이는 어려운일을 해내고 있어요

2024-06-11 08:50 UTC, JiHyeonL requested changes
안녕하세요 종이! 글쓰기 리뷰를 맡게 된 BE 레모네라고 합니다.

종이의 글을 읽으면서 사실 눈물이 찔끔 날 뻔했는데요ㅎㅎㅎ
단순히 슬픔의 감정이 아닌, 감동과 여러 가지 감정이 섞인 복합적인 기분이랄까요😄 
그만큼 몰입감 있고 표현력이 돋보이는 글이라고 생각했어요. 

저도 종이와 비슷한 경험을 해 본 적이 있어서인지 종이가 겪었던 감정, 극복 과정까지 공감하면서 읽을 수 있었어요.
종이의 글쓰기 시리즈는 앞으로도 계속 챙겨볼 것 같아요.

글 작성하시느라 수고 많으셨습니다!
(다른 분들이 모두 approve 하셨으니까 저는 rc 남기겠습니다ㅎㅎ 다시 리뷰 요청 주시면 바로 approve 하겠습니다!)

2024-06-11 09:03 UTC, ss0526100 approved these changes
종이 솔직히 글 읽으면서 울컥했습니다. 종이의 마음이 온전히 잘 느껴져서 그런 것 같아요.

정말 멋있으신 것 같습니다. 제가 이런 글에 감히 피드백을 드릴 수 있을까 싶어요.

틀을 깨고 나온 모습, 그걸 모두에게 드러내는 태도. 너무 대단하십니다. 앞으로도 계속 멋있는 사람으로 남아주세요. 항상 응원하겠습니다.

2024-06-11 16:56 UTC, hyxrxn approved these changes
아토입니다!
종이의 글이 맛집이라는 소문을 듣고... 같은 스터디조로서 한 번 맛보러 왔어요.

최근 유강스에도 남겼지만, 솔직해지는 것은 정말 어려운 일이라고 생각해요.
그런 면에서 이 글엔 많은 용기가 담겨있다고 느껴지네요!

혹시나 행복회로가 필요할 땐 언제든 저를 찾아오시길...
혹시나 캠퍼스가 달라지더라도 편하게 연락 주시길...
It's my pleasure 입니다.

쓸모 없는 복잡한 마음이 들 때 `생각하지마 생각하지마 생각하지마...` 라고 되뇌이며 그 생각을 없애려고 한다고 유강스 때 말했던 기억이 있는데요,
단순하고 긍정적인 생각에 개인적으로 효과적이었던 노래 두 개 추천하고 갑니다!

[Dimitri Vegas & Like Mike vs David Guetta ft. Kiiara - Complicated](https://www.youtube.com/watch?v=w0EF3AxJwLU)
> We can keep it simple, baby. Let's not make it complicated.
> Why don't we just go get naked? Let's not make it complicated.

[Sia - Together](https://www.youtube.com/watch?v=vnfGni4_RlI)
> Can't love me unless you love you too.
> Together we can take it higher!

2024-06-11 16:56 UTC, hyxrxn commented on level2.md
> +레벨1을 돌이켜보면 굉장히 힘들었다. 캡틴 포비가 얘기한 '초반에는 적응을 잘 못하다가 좋아지는 크루를 보면 가장 뿌듯하죠'의 그 크루가 되길 바라면서, 송재하 CTO가 얘기한 '다이아몬드가 되기 위해서는 엄청난 압력과 하중을 견뎌야한다'의 그 다이아몬드가 되길 바랐다. 군대를 제외한 8년 동안 혼자 방 안에서 지내다가, '정지 관성'을 이겨내고 잠실캠퍼
`그래도 내가 힘든건 괜찮지만, 나로 인해 주변 크루들에게 피해를 끼치고 있다는 생각은 견딜 수가 없었다.`

`그래도`는 빼도 될 것 같아요!

2024-06-11 16:56 UTC, hyxrxn commented on level2.md
> +항상 이런식이었다. 내가 원하는 나의 모습을 실현하지 못해 실망하고 다른 사람의 기대에 부응하지 못했다고 착각하며 결국은 그 집단에서 조용히 사라지는 걸 선택했다. 죽고 못 살았던 초중고등학교 동창들도, 항상 주기만 했던 배려심 깊은 사촌 형 누나들도, 미래를 같이 기약했던 군대 동기와 선후임들도, 누가 눈치준 것도 아니고 내가 잘못한 것도 아닌데 서로를
우테코 사람들에게서는 도망치지 않을 수 있는 종이가 되길 응원해요!
좋은 인연 오래 오래 이어갑시닷

2024-06-11 16:56 UTC, hyxrxn commented on level2.md
> +이젠 고민의 방향을 내부로 쏟아야함을 깨달았다. 그 동안 무시해왔던 내 감정의 변화에 귀기울이고, 과거에 대한 후회와 미래에 대한 걱정을 멈추고, 알아차림을 알아차리면서 나 자신에 대한 탐구를 하고 있다. 그리고 가장 중요한건, 삐뚤빼뚤 모난 나의 모습 그대로를 사랑하기로 했다. 이제 크루들한테 조금씩 장난도 칠 수 있다. 우아한테크코스에서 가장 얻어가고
`과거에 대한 후회와 미래에 대한 걱정을 멈추고,`
바람직합니다.

후회와 걱정이 나를 더 발전하게 만들거나 뭔갈 대비할 수 있게 하는 계기가 될 수 있지만,
지금의 종이에겐 편안한 마음이 더 중요하지 않을까 싶어요.

모난 나의 모습... 모났기 때문에 다른 사람보다 내가 제일 많이 사랑할 수 있어요.

2024-06-11 16:56 UTC, hyxrxn commented on level2.md
> +주변에 성장통을 겪고 있는 크루들이 많다. 나도 그렇다. 매일 높은 곳을 올라가기 위해 한 발 한 발 내딛는다. 고개를 떨구면 지나온 길이 짧아 보여 한 숨만 나오고, 고개를 들면 갈 길이 아득히 멀어보인다. 그러나 고개를 들 필요도 내릴 필요도 없다. 지금 당장 해야할 것에 집중하자. 목표를 향해 한 발 한 발 내딛지 않아도 좋다. 잠시 멈춰서서 산수유
`고개를 떨구면 지나온 길이 짧아 보여 한 숨만 나오고, 고개를 들면 갈 길이 아득히 멀어보인다.`
개인적으로 이 문장이 참 맘에 듭니다.

2024-06-12 04:20 UTC, JiHyeonL approved these changes
안녕하세요 종이!
벌써 글쓰기 마지막 날이네요 😄 
approve를 늦게 드려 일정에 차질이 생길까봐 먼저 approve 하겠습니다!  
수고하셨습니다 👍

2024-07-31 02:15 UTC, merged