[레벨 2 글쓰기 미션] 제제(장진우) 미션 제출합니다.
woowacourse/woowa-writing pull request #259
Opened 2024-06-05 13:07 UTC by JINU-CHANG

안녕하세요! 백엔드 제제라고 합니다 😊
레벨2에서의 생각들을 전반적으로 담아보았습니다. 글쓰기 리뷰 잘부탁드립니다!!

2024-06-09 04:46 UTC, unifolio0 approved these changes
레벨 1과는 다른 스타일의 글이네요.
유강스 목표를 잘 지키지 못 했다고 적었는데 글쓰기에 나온 2가지 예시만으로도 잘 진행했다고 생각합니다. 개인적으로 스스로를 잘 컨트롤하기 위해선 나 자신을 아는 것이 선행된다고 생각하거든요.

글 잘 읽고 갑니다!

2024-06-09 04:46 UTC, unifolio0 commented on README2.md
> +레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서 우러나온 목표가 아니어서인지 잘 지켜지지 않았다. 그렇다고 레벨 2에서의
> 레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다.

제제가 생각하는 유강스는 무엇인가요? 저도 레벨 1에는 `나 자신의 단점이라고 생각하는 부분을 고쳐나가는 것`이라 생각했어요. 
하지만 요즘에는 `나 자신을 아는 것`이 아닐까 라는 생각을 합니다. 매주 한 주를 회고하고 피드백을 받으면서 이 목표에 대해서 고민하는 시간을 가지는 것을 보면서 말이죠.
유강스를 조금 더 가볍게 생각해도 좋을 것 같아요

2024-06-10 08:40 UTC, donghoony requested changes
제제 안녕하세요 👋🏻 유강스에서 계속 봐왔던 터라 글을 읽는 데에 편했습니다. 어떤 과정을 통해 성장해왔는지가 눈에 보여서 더 좋았네요.

다른 크루에게도 이야기했던 내용이지만, 저는 코딩 부트캠프를 진행하면서 어떻게 많은 크루들이 '나'의 존재에 대해서 고민하게 될까? 라는 궁금증을 가졌어요. 미션만 진행하기에도 바쁜데 어떻게 나의 상태를 알아보며 성장할 겨를까지 챙겨가는 건지, 정말 신기했거든요.

생각을 해 보고, 곧이어 저도 이런 고민을 하게 되면서 한 가지에 몰두하면, 정말 집중하는 나의 본모습이 보인다고 생각했어요. 이런 과정에서 나의 학습 과정에서 더 나아가기 위한 계획도 챙겨갈 수 있었던 거죠 🙂

제제가 유강스를 통해서, 테코톡과 미션을 통해서 자신을 알아가는 모습이 정말 멋있습니다~! 앞으로도 쭉쭉 달려보자고요 🏃🏻‍➡️ 레벨 2 고생했어요~

- 문장이 어우러질 수 있도록 몇가지 코멘트를 남겼으니 선택적으로 반영해주세요. 😄

2024-06-10 08:40 UTC, donghoony commented on README2.md
> +레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했
같은 유강스 조로서 제제가 성장하는 과정이 보여 신기했어요. 어느 순간부턴가 자신의 모습이 보이면서 불편해하던 때도 있었고, 그 모습을 인정하고 나아가려는 모습도 보였어요. 🥹 멋있다고 느꼈습니다 정말!!


- 문장이 조금 길어서 정리할 필요가 있어보입니다. 뒤쪽 문장을 조금 다듬어볼까요? 아래는 제 생각이 들어갔으니 참고만 해주세요!

```suggestion
레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했고 가면을 쓰고 살아갔다. 그런데 우테코에서는 자꾸 가면 속의 나를 툭툭 건드렸다. 이야기하고 싶지 않았지만 입 밖으로 계속 꺼내게 만들었다. /- 맥락이 하나 더 필요하다고 느껴져요 -/ 크루들과 고민을 나누면서 나의 고민이 지극히 평범하며, 완벽하다고 생각했던 사람도 끊임없이 고민하고 개선하며 현재의 모습을 이뤄냈다는 것도 알아냈다. 마음이 편안해졌고 솔직한 나를 드러낼 수 있었다.
```

2024-06-10 08:40 UTC, donghoony commented on README2.md
> +방학을 마치고 돌아온 나는 열정으로 가득 차 있었다. 그동안 스프링을 여러 번 사용해봤지만 제대로 알고 사용한 적은 없었다. 프로젝트를 완성하는 데 바빠 남들이 하는 대로 코드를 따라쳤던 것 같다. 그러다보니 누군가 내 코드에 대해 물어보면 자신 있게 답할 수 없었다. 레벨 2를 시작하면서는 스프링을 깊이 있게 학습하기로 다짐했다. 미션을 시작하자 여러
- `-것 같다`의 사용을 줄여 봅시다. 독자에게 확신을 가져다 주자고요!
- 접속사가 없어도 문장 흐름에 부담이 없다면, 간결하게 문장을 챙겨볼까요?

```suggestion
방학을 마치고 돌아온 나는 열정으로 가득 차 있었다. 그동안 스프링을 여러 번 사용해봤지만 제대로 알고 사용한 적은 없었다. 프로젝트를 완성하는 데 바빠 남들이 하는 대로 코드를 따라쳤다. 누군가 내 코드에 대해 물어보면 자신 있게 답할 수 없었다. 레벨 2를 시작하면서는 스프링을 깊이 있게 학습하기로 다짐했다. 미션을 시작하자 여러 개념이 등장했고 하나씩 깊게 공부하며 완전히 내 것으로 만드는 과정이 재밌었다. 특히 하나를 깊게 공부할 때 새롭게 알게 된 지식들이 가지를 뻗어 풍부해지는 그 느낌이 좋았다. 시간 가는 줄 모르고 재밌게 공부했다.
```

2024-06-10 08:40 UTC, donghoony commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
- 하나의 문단에는 하고자하는 주제 하나가 들어가면 좋습니다. 문장끼리의 협력을 통해 이끌어내면 좋은데요, 생각보다 이 문단의 문장들이 어우러진다는 느낌을 받기 어렵습니다.
- `테코톡으로 정신없는 시간들을 보냈다.`, `한 가지에 집중하면 거기에만 완전히 몰입하는 성격이다.`, `테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다.`는 서로 다른 이야기를 하는 느낌이 들었습니다 👀
- 글 전체적으로 확인해보면서 튀는 문장이나 불필요한 문장을 제거해보고, 여러가지 이야기를 한다면 문단을 나눠보는 것도 방법이겠네요!

아래는 제 생각이 들어갔으니, 이런 방향이면 어떨까? 라고 참고만 해주세요 😄

```suggestion
테코톡으로 정신없는 시간들을 보냈다. 성공적으로 마무리했지만, 번아웃이 찾아와 이후의 일들이 손에 잡히지 않았다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데, 생각보다 오랜 시간 지속됐다. 예전에도 이런 적이 있었다. 중요한 프로젝트를 마무리했을 때에도, 우테코 합격 발표를 들었을 때에도 그랬다. 한동안 공부가 손에 잡히지 않았다.
예전에는 시간이 해결해주길 기다리며 무기력한 나날을 지냈다. 이번에는 새로운 것들을 시도해보고자 했다. 공부하는 장소를 옮겨봤다. 하루는 창가쪽에, 하루는 쇼파 근처에서 공부했다. 환경에 변화를 주니 익숙함으로 인해 늘어졌던 마음과 자세가 긴장함과 함께 집중력이 살아나는 것을 느꼈다.
이전의 힘들었던 순간들과 현 상황을 비교해봤다. 열심히 달리다가 한순간에 힘이 확 빠지는 나는, 적당한 휴식이 필요한 사람이었다. 매일 새로운 지식들이 쏟아지고 그것이 채 소화되기도 전에 다음날 새로운 지식이 비집고 들어오려고 한다. 학습해야한다는 강박은 제쳐두고, 저녁에 일찍 퇴근해 머릿속을 환기할 시간을 충분히 가졌다. 새로운 지식들이 들어갈 공간이 생기기 시작했고 미션에 집중할 수 있었다.
```

2024-06-11 06:01 UTC, ashsty approved these changes
안녕하세요 제제~ 이번에 같은 데일리조로 만나게 된 애쉬예용~~!

제제는 유강스를 통해 스스로 많이 성장하셨다고 느끼시는 것 같아서 신기했어요. 너무 아쉽다 제제랑 같은 조였어야 하는데...

사람이 늘 좋은 일만 있을 수도 없고 나쁜 일만 있을 수도 없는 거겠죠? 가끔씩 그것들이 짧은 간격으로 몰려 오는 경우가 있기는 하지만, 그럴 때마다 사람이 살면서 크고 작은 기복이 있는 건 어쩔 수 없는 것 같아요. 중요한 건 기복이 없어지는 게 아니라 그런 기복이 찾아올 때마다 어떻게 대처하면 좋은지 내가 점점 적응하며 알아가는 거겠죠! 이번 경험이 그런 일의 단초가 되었으면 좋겠다는 생각이 드네요.

날씨도 점점 더워지고 있는데, 이렇게 된 김에 이번 방학에는 공부 생각하지 않고 푹 쉬어보는 건 어떨까요? ㅎㅎ

2레벨 정말 고생하셨습니다!
방학 잘 보내시고 3레벨 때는 조금 더 즐거운 모습으로 다시 보도록 해용~~!!!

2024-06-11 06:33 UTC, chlwlstlf reviewed
안녕하세요 제제! 텐텐이에요😊

다른 분들이 자세하기 예시까지 들면서 리뷰를 해주셔서 할 게 별로 없었습니다..!
문단 잘 바꿔주시면 리뷰어가 문장 선택해서 피드백하기도 더 수월할 것 같습니다ㅎㅎ

방학 잘 보내시고 레벨3도 화이팅이에요🔥🔥

2024-06-11 06:33 UTC, chlwlstlf commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
한 가지에 너무 열심히 몰입하면 번아웃이 오기 마련이죠.. 레벨2를 통해 '새로운 공간에서 공부하기' 라는 해결책을 찾은 것 같아서 다행이네요ㅎㅎㅎ😊😊

다른 분들이 말씀하셨지만 이야기의 흐름이 바뀔 때마다 문단을 변경해주면 좋을 것 같아요!

2024-06-11 11:24 UTC, skylar1220 requested changes
안녕하세요 나의 라임 오렌지 나무 jeJe 당신의 친구 커비에요🍊

한 문단 한 문단 읽으면서 제제가 고민했던 그 모습이 모두 떠올랐어요.
고민은 알았지만 그 고민을 제제가 내면적으로 어떻게 해결해갔는지는 몰랐는데 ,
이렇게 글로 알게되니 비로소 제제의 레벨 2를 온전히 이해한 기분이 들어서 좋았어요☺️

항상 고민이 많았던 우리들이지만 글을 보니 그 고민들이 점점 옅어져가는 게 느껴져요.
그 말인 즉슨, 앞으로 제제가 어떤 고민을 하든 점차 옅게 만들 수 있는 능력이 충분히 있는 사람이라는 것 아닐까요? 고민이 드는 순간은 답답하겠지만 지금까지의 제제가 가볍게 만들어냈던 고민들을 믿으며 계속 나아가면 될 것 같아요! 

고민이 유독 많았던 레벨 2였던 만큼 우리 모두 수고 많았어요☺️

2024-06-11 11:24 UTC, skylar1220 commented on README2.md
> +레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했
1. 약간의 문장 수동형 수정을 해보았습니다!
2. 속의 모습이 꺼내지게 했다 - 평범한 고민이었다 사이의 내용이 약간 뛰어넘는 느낌이 들어요. 연결 문장을 추가하거나 단락을 나누면 좋을 것 같아요!
```suggestion
레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했고 가면을 쓰고 살아가는 것 같았다. 그런데 우테코에서는 자꾸 가면 속의 내가 툭툭 건드려졌다. 이야기하고 싶지 않았지만 이야기를 계속 꺼내게 했다. (이 사이의 연결하는 문장이 있으면 좋을 것 같아요) 크루들과 고민을 나누며 조금씩 깨닫게 되는 것이 있었다. 내 고민들이 지극히 평범한 고민들이라는 것, 그리고 완벽하다고 생각했던 사람들도 끊임없이 고민하고 개선하며 현재의 모습을 이루었다는 것이다. 그것들을 깨닫는 순간부터 마음이 편안해졌고 솔직한 나를 드러낼 수 있었다.
```

2024-06-11 11:24 UTC, skylar1220 commented on README2.md
> +그런데 점점 답이 정해져 있지 않은 추상적인 질문들을 받기 시작했다.개념 자체도 어려웠고, 궁금한 내용을 열심히 검색해도 이해하기 어려웠다. 논리적으로, 근거를 가지고 답변해야 한다는 것을 알고 있었지만, 막상 리뷰어가 그런 질문을 남기면 쉽게 생각을 정리하지 못했다. 어떻게 해결해야 할지 고민하다가 오랜 시간을 허비하곤 했다. 이런 시간이 반복되면서 논
마지막 문장이 없다면 어떨까 생각해봤어요.
그러면 '변화'에 대한 서술이라는 이 문단의 응집도가 더 올라갈 것 같아요!

2024-06-11 11:24 UTC, skylar1220 commented on README2.md
> +레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서 우러나온 목표가 아니어서인지 잘 지켜지지 않았다. 그렇다고 레벨 2에서의
1. 레벨 2의 목표를 만족스럽지 못하지만 세웠다.
2. 잘 지켜지지는 않았다.
3. 하지만 그와 상관없이 나를 더 잘 알게되었던 레벨2였다.

의 흐름인 것 같은데, 뒤의 내용을 서술하기 위해서는 3번만 있어도 되지않을까, 1, 2번의 서술이 필요할까? 라는 생각이 들어요.
오히려 1,2번 서술이 있음으로써 독자로 하여금 레벨2 유강스 목표와 관련된 내용이 서술되려나? 하는 혼란을 줄 수도 있을 것 같아요!

2024-06-11 11:24 UTC, skylar1220 commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
마지막 두문단에 거쳐서 레벨2에서 겪었던 고난(?), 스스로의 해결 방법을 서술했네요!
그래서 그런지 지금은 적용했던 해결방법을 이야기하고 급 끝난 느낌이 들어요😂

이런 레벨2의 해결들을 통해 공통적으로 배우게된 점이라든지,
레벨 3에서도 여러 고난이 있겠지만 어떤 마음 가짐으로 나가고자 하는지,
등의 내용으로 마무리를 지어보는 건 어떨까요?

2024-06-11 11:24 UTC, skylar1220 commented on README2.md
> +그런데 점점 답이 정해져 있지 않은 추상적인 질문들을 받기 시작했다.개념 자체도 어려웠고, 궁금한 내용을 열심히 검색해도 이해하기 어려웠다. 논리적으로, 근거를 가지고 답변해야 한다는 것을 알고 있었지만, 막상 리뷰어가 그런 질문을 남기면 쉽게 생각을 정리하지 못했다. 어떻게 해결해야 할지 고민하다가 오랜 시간을 허비하곤 했다. 이런 시간이 반복되면서 논
제제가 고민했던 모습이 떠올라서 공감하며 읽었습니다!
역시 구체적인 경험을 단순하게 표현한 문장이 가장 좋은 문장이라는 생각이 드네요☺️

2024-06-11 18:25 UTC, jinchiim reviewed
안녕하세요 제제! 🍊
멋지게 테코톡을 끝낸 모습이 기억에 남는데,
유연성 강화 글에서 언급되어 좋았습니다! 다음 유연성 강화 목표도 궁금하네요 
글 잘 봤습니다!

2024-06-11 18:25 UTC, jinchiim commented on README2.md
레벨 1에서는 적절한 부주제를 통해 문단을 나눠주셨던 것 같은데
레벨 2에서는 문단이 나뉘어져 있지 않아 개인적으로 아쉬운 것 같습니다! 🥹

2024-06-11 18:25 UTC, jinchiim commented on README2.md
> +레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서 우러나온 목표가 아니어서인지 잘 지켜지지 않았다. 그렇다고 레벨 2에서의
이부분이 조금 헷갈렸는데요!
`레벨 2의 새로운 목표는` 이라는 문장을 통해 레벨 1에서 어떤.. 실패를 겪어 이번에는 신중하게 정하고 싶었다는 느낌으로
저는 받아들여지더라고요!

제제의 레벨1도 실패한 것은 아니니 `새로운 목표도` 로 바꾸는 건 어떨지 의견을 내봅니다!

2024-06-11 18:25 UTC, jinchiim commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
학습과 더불어 스트레스나 어려움을 해소하는 방법에 대해 배워나가는 과정 같네요!
저도 무엇보다 스트레스를 다루는 것이 가장 어렵다고 생각합니다 🥲

그 와중에 이전과 똑같이 행동하기 보다는 환경을 바꾸는 등의 시도를 한 제제가 멋지네요!

2024-06-12 01:52 UTC, jminkkk reviewed
안녕하세요 제제 !
리뷰가 늦었습니다 😭

다른 크루들이 이미 좋은 피드백을 작성해주신 것 같아서 큰 피드백은 없네요!
글을 읽으면서 레벨2동안 저와 비슷한 생각을 많이 하신 것 같아 공감이 되는 글이었습니다 👍

레벨2 마무리 잘 하시고 방학 잘 보내시길 바랍니다 🍀

2024-06-12 01:52 UTC, jminkkk commented on README2.md
> +레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했
**레벨 1 유강스 목표는 "솔직해지자"였다.** 
와 같이 목표를 강조해보아도 좋을 것 같아요 !

2024-06-12 01:52 UTC, jminkkk commented on README2.md
> +방학을 마치고 돌아온 나는 열정으로 가득 차 있었다. 그동안 스프링을 여러 번 사용해봤지만 제대로 알고 사용한 적은 없었다. 프로젝트를 완성하는 데 바빠 남들이 하는 대로 코드를 따라쳤던 것 같다. 그러다보니 누군가 내 코드에 대해 물어보면 자신 있게 답할 수 없었다. 레벨 2를 시작하면서는 스프링을 깊이 있게 학습하기로 다짐했다. 미션을 시작하자 여러
저도 공감이 되는 내용들이 많네요 😀
레벨 2동안 제제가 학습에 대한 깊은 고민을 했고 그 과정을 엿볼 수 있게 작성된 것 같아 내용이 재미있네요 👍

2024-06-12 05:39 UTC, Dobby-Kim approved these changes
안녕하세요 제제!
리뷰가 많이 늦었습니다🥹🥹

진솔하게 작성해주신 글 잘 읽었습니다.
사회로 진출하기 전인 이 시기에 누구나 드는 고민을 풀어내주셨네요

전반적으로 너무 잘 작성해주셨는데, 전체적으로 가독성을 위해 적절한 개행이 추가되었으면 하네요!

레벨 2 고생하셨구, 레벨 3에서 다시 뵙겠습니다!

2024-06-12 05:39 UTC, Dobby-Kim commented on README2.md
> +레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서 우러나온 목표가 아니어서인지 잘 지켜지지 않았다. 그렇다고 레벨 2에서의
```suggestion
레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족을 극복하는 경험을 통해 더 나은 내가 될거라 기대했다. 분명 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했고, '스스로 잘 컨트롤하기'라는 목표를 세웠다. 하지만 마음 속 깊은 곳에서 우러나온 목표가 아니었기에 잘 지키지 못했다. 그렇다고 유연성 강화를 실패한 것은 아니다. 오히려 나를 더 잘 알게 되었다고 말하고 싶다. 여러 상황 속에서의 내 모습과 생각들을 계속해서 관찰했고, 이 과정에서 든 생각과 느낀 감정들을 쭉 풀어보고자 한다.
```

잘 지켜지지 않았다 -> 그렇다고 실패한건 아니다 라는 맥락이 조금 어색해서 여러 번 읽게된 것 같습니다!
뭔가 뚝딱거리면서 부드러운 맥락을 표현하려고 조금 고쳐보기는 했는데 참고해주시면 감사하겠습니다ㅎㅎ

2024-06-12 05:39 UTC, Dobby-Kim commented on README2.md
> +방학을 마치고 돌아온 나는 열정으로 가득 차 있었다. 그동안 스프링을 여러 번 사용해봤지만 제대로 알고 사용한 적은 없었다. 프로젝트를 완성하는 데 바빠 남들이 하는 대로 코드를 따라쳤던 것 같다. 그러다보니 누군가 내 코드에 대해 물어보면 자신 있게 답할 수 없었다. 레벨 2를 시작하면서는 스프링을 깊이 있게 학습하기로 다짐했다. 미션을 시작하자 여러
아루가 말씀해주신 것처럼 많은 사람들이 한국인 겸손특성상 자신의 의견을 애둘러 표현하기 위해 `~것 같다`라는 표현을 많이 사용~~하는 것 같습니다~~ 한다고 합니다.
실제로는 글이나 기업 자소서에서 해당 표현을 많이 사용하면 자신감이 떨어져보이게 하고, 글의 신뢰도를 낮춘다고 하네요!

2024-06-12 05:39 UTC, Dobby-Kim commented on README2.md
> +그런데 점점 답이 정해져 있지 않은 추상적인 질문들을 받기 시작했다.개념 자체도 어려웠고, 궁금한 내용을 열심히 검색해도 이해하기 어려웠다. 논리적으로, 근거를 가지고 답변해야 한다는 것을 알고 있었지만, 막상 리뷰어가 그런 질문을 남기면 쉽게 생각을 정리하지 못했다. 어떻게 해결해야 할지 고민하다가 오랜 시간을 허비하곤 했다. 이런 시간이 반복되면서 논
아는 것의 척도는 질문의 질로 나타난다고 하죠!
제제가 계속 스스로 집요하게 `왜?`를 떠올리고 답하다 보면 결국 성장한 자신의 모습을 볼 수 있을거라 생각해요.
응원합니다 :>

2024-06-12 05:39 UTC, Dobby-Kim commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
저는 고3/N수생을 대상으로 수능 수학 수업을 7년째 해오고 있는데, 항상 모든 학생들이 겪는 현상이라 많이 공감이 되네요.
다들 6,9평을 보거나, 심지어 수능 한 달전에 슬럼프가 와서 힘들어 하는 모습을 보이곤 합니다.
사람마다 슬럼프를 이겨내는 방법을 가지각색이지만, 저는 학생들이 이런 고민을 풀어놓을 때 항상 `공부가 하기 싫을 때에는 공부를 해라`라고 말합니다.
결국에는 해야되는 것들이고, 수능이라는 단기적인 목표가 있기 때문에 이렇게 말했습니다. 결국 저희가 처한 상황도 다르지 않았다고 생각해요!
그리고 같은 상황에서 제제 또한 여러 방법으로 공부하기 싫을 때에도 공부를 한 것 같네요!
힘들 때도 있겠지만 저희 모두 결국 해낼거라 생각합니다.
응원해요

2024-06-12 06:02 UTC, nayonsoso commented
안녕하세요 제제, 산초입니다☺️

여러 부분이 공감되었던 글이었습니다.
저도 자신감은 부족하지만 그 실체를 들키고 싶지 않아 감추려 했고,
우테코에 와서 그것을 드러내고 나서야 후련함을 느꼈었습니다.
또 테코톡을 마무리하고 한순간 번아웃이 왔던 것도 많이 공감이 되었네요😂

제제의 레벨1의 목표인 ‘솔직해지기’를 잘 지킨 글이라는 생각이 들었습니다.
솔직하게 제제의 경험을 공유해주셔서 저도 더 제제를 이해하고, 몰입감 있게 글을 읽을 수 있었습니다.
그리고 저도 이런 글을 쓰고 싶다고 생각했습니다🔥

한가지 피드백드리고 싶은 것은,
제제가 적은 레벨2의 다양한 경험들을 통해 종합적으로 어떤 생각을 하게 되었는지에 대한
마무리 문단이 있으면 좋을 것 같습니다.
물론 지금의 마지막 문단에 ‘내게 적당한 휴식이 했던 것 같다’라는 내용이 있긴 하지만,
제제의 레벨2 목표를 종합적으로 정리해주진 않는다는 생각이 들었습니다.

이 부분만 제외하면 정말 훌륭한 글이었다 생각합니다🤗
생각 자체가 깊으신 분 같다 느꼈습니다.
좋은 글 잘 읽었습니다🌷

2024-06-12 06:02 UTC, nayonsoso approved these changes
안녕하세요 제제, 산초입니다☺️

여러모로 공감되는 글이었습니다.
저도 자신감은 부족하지만 그 실체를 들키고 싶지 않아 감추려 했고,
우테코에 와서 그것을 드러내고 나서야 후련함을 느꼈었습니다.
또 테코톡을 마무리하고 한순간 번아웃이 왔던 것도 공감이 되었습니다😂

제제의 레벨1의 목표인 ‘솔직해지기’를 잘 지킨 글이라는 생각이 들었습니다.
솔직하게 제제의 경험을 공유해주셔서 저도 더 제제를 이해하고, 몰입감 있게 글을 읽을 수 있었습니다.
그리고 저도 이런 글을 쓰고 싶다고 생각했습니다🔥

한가지 피드백드리고 싶은 것은,
제제가 적은 레벨2의 다양한 경험들을 통해 종합적으로 어떤 생각을 하게 되었는지에 대한
마무리 문단이 있으면 좋을 것 같습니다.
물론 지금의 마지막 문단에 ‘내게 적당한 휴식이 했던 것 같다’라는 내용이 있긴 하지만,
제제의 레벨2 목표를 종합적으로 정리해주진 않는다는 생각이 들었습니다.

이 부분만 제외하면 정말 훌륭한 글이었다 생각합니다🤗
생각 자체가 깊으신 분 같다 느꼈습니다.
좋은 글 잘 읽었습니다🌷

2024-06-12 06:30 UTC, chlwlstlf approved these changes

2024-06-12 08:13 UTC, JINU-CHANG commented on README2.md
> +테코톡으로 정신없는 시간들을 보내기도 했다. 한가지에 집중하면 거기에만 완전히 몰입하는 성격이다. 테코톡을 마무리하자 힘이 풀리면서 아무것도 하기 싫은, 일명 번아웃 상태가 됐다. 처음에는 며칠 쉬면 괜찮아질 줄 알았는데 생각보다 오래시간 지속됐다. 가만히 들여다보니 예전의 내모습이 오버랩됐다. 중요한 프로젝트를 마무리한 후, 우테코 합격 발표를 들은 후
맞아요 .. 😭 마무리가 없이 끝낸게 찝찝하게 남아있긴 했습니다. 적용해볼게요 !!

2024-06-12 08:43 UTC, JINU-CHANG commented on README2.md
> +레벨 2의 새로운 목표는 신중하게 세우고 싶었다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서 우러나온 목표가 아니어서인지 잘 지켜지지 않았다. 그렇다고 레벨 2에서의
오홍 !!! 헷갈릴수도 있겠네요 수정해보도록 하겠습니다 👍

2024-06-12 08:50 UTC, JINU-CHANG commented on README2.md
> +레벨 1 유강스 목표는 솔직해지자였다. 우테코에서의 생활 그리고 유강스 목표는 나를 많이 변화시켰다. 방학 때 그동안 일어난 변화들을 생각해본 적이 있다. 그때 느꼈던 가장 큰 변화는 자신감이었다. 우테코에 오기 전까지는 나의 부족한 모습을 다른 사람에게 들키는 것이 싫어서, 부끄러워서 감추는데 급급했다. 겉으로는 아닌 척했지만 늘 마음 한 구석이 답답했
감사합니다 😊

2024-06-12 08:58 UTC, JINU-CHANG commented on README2.md
> +방학을 마치고 돌아온 나는 열정으로 가득 차 있었다. 그동안 스프링을 여러 번 사용해봤지만 제대로 알고 사용한 적은 없었다. 프로젝트를 완성하는 데 바빠 남들이 하는 대로 코드를 따라쳤던 것 같다. 그러다보니 누군가 내 코드에 대해 물어보면 자신 있게 답할 수 없었다. 레벨 2를 시작하면서는 스프링을 깊이 있게 학습하기로 다짐했다. 미션을 시작하자 여러
기업 자소서에서는 확신의 말투가 좋을 것 같으나, 개인적인 생각을 표현하는 글에서는 조심스럽게 감정표현을 하다보니 `~것 같다`라는 표현을 사용하게 된 것 같네요! 많이 사용하는 건 좋지 않은 것 같아 줄여보도록 하겠습니다.

2024-06-12 08:59 UTC, skylar1220 approved these changes

2024-06-12 09:12 UTC, donghoony approved these changes
리뷰 야무지게 반영했네요 훨씬 읽기 좋아졌어요 👏🏻

2월에 처음 보는 사람들이 서로 마음 터놓고 이야기하기까지 걸린 시간이 정말 짧아요. 정말 서로를 이해할 시간이 충분했을까요 🧐
개인적으로는 개개인이 마음을 열어준 게 가장 크다고 생각해요. 함께 있더라도 서로 문을 닫아둔다면 지금의 잠실 분위기가 있었을까, 데일리 안에서의 분위기가 있었을까 생각해보기도 합니다 😅 그래서 그런 사람들에게 참 고맙다고 이야기하고 싶네요 ! 솔직하게 마음을 여는 데만에도 큰 용기가 필요하니깐요.

레벨 2 수고 많았고, 앞으로의 레벨에서도 꾸준히 성장하기를 기대합니다~!~! 달려보자고 🔥

2024-06-12 09:12 UTC, donghoony commented on README2.md
> +레벨 1의 유강스 목표가 나에게 좋은 변화를 가져다줬기 때문에, 레벨 2의 새로운 목표를 세우기 전에 신중하게 고민해봤다. 다시 한 번 부족한 모습을 극복하는 경험을 함으로서 더 나은 내가 될 수 있겠다고 기대했다. 그런데 분명, 고치고 싶은 부분은 많았지만 좋은 목표를 찾지 못했다. 스스로 잘 컨트롤하기 라는 목표를 세우기는했지만 마음 속 깊은 곳에서
👀 
`세우기는했지만` -> `세우기는 했지만`

2024-06-12 10:15 UTC, jinchiim approved these changes

2024-06-12 10:17 UTC, jinchiim approved these changes

2024-06-12 12:23 UTC, jminkkk approved these changes

2024-06-13 06:27 UTC, HoeSeong123 commented
안녕하세요 제제~ 초롱입니다!
글 정말 잘 읽었습니다.

전체적으로 글이 꾸밈없이 솔직하게 적혀있는 것 같아서 좋았어요.
레벨 1 유연성 강화 목표였던 `솔직해지자`가 확실하게 이루어진 것 같은 글이었습니다🤭

레벨 2에 같은 조였는데도 제제가 이런 고민을 하고 여러 시도를 하고 있었다는 것을 알아채지 못했다는 사실이 조금 미안해지네요😥
그만큼 다양한 대화를 나눠보지 못한 것 같아 내심 아쉬움이 많이 듭니다.
기회가 된다면 저도 제제의 고민 해결에 도움이 되고 싶네요. (레벨 2가 끝나가는 이 시점에 이런 말을 하는 게 좀 웃기긴 하네요)

그래도 이미 많은 크루들이 제제를 도와준 것 같아 다행입니다.
그리고 제제 스스로도 자신을 찾아가기 위한 많은 노력을 한 것 같네요.
저도 아직 스스로를 잘 모르겠는데 다양한 시도를 해봐야겠어요. 하면서 방향을 잃어버리면 그 때는 제제에게 도움을 구하러 가겠습니다 ㅋㅋ

레벨 2 동안 제제에게 많은 도움을 받은 것 같습니다.
진짜 특히 밥 관련해서는 최고....👍
항상 농담 반 진담 반(솔직히 농담 20 진담 80)으로 제제에게 메뉴 선택을 맡겼는데 매번 잘 받아줘서 너무 고마웠어요.
저 같았으면 진짜 짜증 백 번 냈을 거 같은데..단 한 번도 짜증내지 않고 매번 진지하게 메뉴를 골라줘서 너무 고맙습니다 진짜

그거 말고도 제가 지켜본 제제는 뭘 부탁하든 싫어하지 않고 진지하게 들어주는 것 같아요.
정말 큰 강점이라고 생각합니다.

레벨 3 가서도 항상 화이팅하고 스트레스 받지 않고 잘 지내세요.
저는 어떤 상황이든 행복이 1순위라고 생각하는 사람이라 제제도 늘 행복하게 살아갔으면 좋겠고 그렇게 되도록 저도 도움이 되고 싶네요.
늘 지금처럼 주변 사람도 챙기고 자신도 잘 돌아보는 사람으로 지냈으면 좋겠습니다.
행복하세요☺️

2024-07-31 02:15 UTC, merged