[레벨 2 글쓰기 미션] 해나(공혜연) 미션 제출합니다.
woowacourse/woowa-writing pull request #264
Opened 2024-06-05 13:38 UTC by hxeyexn

### 안녕하세요~ 안드로이드 6기 해나입니다! 🦋
리뷰 잘 부탁드리겠습니다! 편하게 읽어주세요 😊
Level2도 정말 고생많으셨습니다!

`1편` : [해나 Lv1 글쓰기 미션 바로가기](https://github.com/hxeyexn/woowa-writing/blob/main/Lv1.md)
`2편` : [해나 Lv2 글쓰기 미션 바로가기](https://github.com/hxeyexn/woowa-writing/blob/main/Lv2.md)

2024-06-07 08:32 UTC, lurgi reviewed
안녕하세요 해나! 처음 인사드리는 것 같네요! 🙇‍♂️

전체적으로 군더더기 없던 글이라고 생각이 들어요! 챕터별로 나눠서 키워드를 만들어 주셔서 읽기 쉬었습니다! 그래서 술술 읽혔던 것 같아요~

피드백 짧게 남겨 드렸습니다.
좋은 글 감사합니다 해나!

2024-06-07 08:32 UTC, lurgi commented on Lv2.md
> +마찬가지로 이때 나에게도 쉼표가 필요했던 순간이었다.
해나에게 쉼표가 어떤 의미인지도 궁금하네요! 단순히 리프레쉬를 위한 휴식일까요? 아니면 그 이상의 의미를 가지고 있는 것일까요? 조금 더 궁금해지는 대목이었어요~

2024-06-10 06:08 UTC, healim01 approved these changes
안녕하세요 해나! 
글쓰기 미션을 통해 만나뵙게 되어서 반가워요!

글이 정말 바르고 차분하게 느껴져서 저도 덩달아 차분하게 해나의 감정을 읽어볼 수 있던거 같아요. 해나가 다음 레벨에서는 예쁜 윤슬과 같이 쉼표가 있는 삶을 그릴 수 있으면 좋을거 같아요! 
레벨 2 정말 수고 많으셨습니다!

2024-06-10 06:08 UTC, healim01 commented on Lv2.md
> +이 와중에 테코톡이 끝난 나를 기다리고 있는 것은 쉼이 아니라, 마감일이 4일밖에 남지 않는 3, 4단계 미션이었다.
테코톡을 하면서 미션을 진행하는 건 정말 힘든거 같아요. 저도 이번 레벨2 페어미션을 진행하며 테코톡을 진행했는데 정말 정신이 없더라구요. 자꾸 돌아보면 아쉬운 것들 투성이지만 의식적으로 생각을 하지 않으려고 노력하는거 같아요.

2024-06-10 06:08 UTC, healim01 commented on Lv2.md
> +잠깐의 침묵이 곡의 흐름을 더욱 돋보이게 하고, 아름답게 만들어준다.
정말 멋진 표현을 사용해서 글을 작성해주신거 같아요! 해나에게 쉼표가 부족했음을 감각적으로 표현해주셨네요!

2024-06-10 18:48 UTC, Junyoung-WON reviewed
안녕하세요, 해나!
너무 좋은 글을 재미있게 잘 읽었어요~~
챕터로 나눠놓은 것이 보기에도 편했고, 쉽게 몰입할 수 있어서 좋았습니다!

레벨 2때에 해나와 더 친해지고 더욱 많은 이야기를 나눌 수 있었던 덕분에, 해나의 글이 더 공감되고 잘 몰입되었던 것 같아요. 사실 제가 바라보았던 해나는 항상 차분하고 쉽게 무너지지 않을 것 같은, 그런 이미지의 크루였어요.
하지만 이전 글과 레벨2의 글에서 해나의 솔직한 생각과 감정들을 보고 느낄 수 있었어요. 여러 고민과 걱정이 많을텐데도, 힘들고 어려운 순간들을 겪으면서도, 이것들을 이겨내고 앞으로 나아가는 해나가 정말 대견하고 멋있는 것 같습니다.

이번 레벨에서 정말 많은 고생을 해주었던 해나가, 이번에 스스로에게 선물한 쉼표로 큰 위로가 되었던 것 같아 다행입니다! 앞으로도 여러 음표들과 쉼표들을 가지고, 해나만의 멋지고 예쁜 노래를 작곡해나갔으면 좋겠습니다~!

2024-06-10 18:48 UTC, Junyoung-WON commented on Lv2.md
> +바쁜 와중에 어찌어찌 테코톡을 끝내긴 했지만 사실 썩 만족스럽지 않다. 준비가 부족하기도 했고, 준비한 만큼 다 쏟아내지도 못했다.
저도 레벨 2 미션이 테코톡과 합쳐지니, 거대한 쓰나미가 되어서 저를 덮치는 듯했어요. 미션만으로도 충분히 버거운데, 테코톡이라뇨...

그럼에도 저는 해나가 테코톡을 너무 잘했고 정말 잘 마무리했다고 생각해요!! 하지만 끝났을 당시에 해나가 만족스러워하지 않은 것 같아서, 저도 속상하고 안타까웠습니다. 해나가 테코톡 준비를 꾸준히, 열심히 해오던 것을 옆에서 봐왔기 때문에 더욱 공감했던 것 같아요.
시간이 지난 지금도 여전히 아쉬워하고 속상해 할 수도 있겠지만, 정말로 잘했고 또 정말 멋있었다고 이야기해주고 싶어요~

2024-06-10 18:48 UTC, Junyoung-WON commented on Lv2.md
> +사실 항상 나를 가만히 두지 못한 건 나 자신이었다. 그냥 가던 길을 가면 될 텐데 항상 브레이크를 내가 건다. 참 아이러니하다.
사실 이 부분을 처음 읽었을 때는 잘 이해되지 않았어서, 여러 번 읽으면서 이해할 수 있었어요...!

앞서 `쉼표`라는 표현을 활용해서 '쉬어감, 휴식'을 주었다는 이야기를 했는데, 이 문장에서는 `브레이크`라는 표현이 나오면서 동일한 의미('쉬어감, 휴식')를 가진 단어라고 생각했어요. 그래서 "쉼표와 비슷한 의미를 나타내는 표현일까?" "그런데 왜 브레이크를 스스로에게 걸고 있는지에 대해서 의문을 품는 걸까?" 라는 궁금증이 생겼던 것 같아요.

여기서의 `브레이크`는
- '성장하는 나', '마라톤을 달려가는 나'라는 관점에서, 스스로가 자신의 성장을 멈추게하는 것을 의미한 것이거나,
- 이 뒤에 나오는 `흘러가는 윤슬`처럼 흘러가는 대로 두지 않고 굳이 멈춰세우는 것을 의미한다.

라고 이해했어요. 이전에 해나가 이야기했던 `완벽주의 성향`, 또는 이번 글에서의 `원하는 대로 이루지 못했다는 실망감`이 여기서 말하는 "브레이크"인 것 같았어요. 제가 잘 이해한 것이 맞을까요?

2024-06-10 18:48 UTC, Junyoung-WON commented on Lv2.md
> +**그냥 흘러가는 대로 즐기자. 햇빛이 비치어 반짝이는 한강의 윤슬처럼**
이 문장의 표현도, 그리고 윤슬이라는 단어도 너무 예쁜 것 같아요!

인생은 항상 원하는대로 이룰 수 없고, 그런 삶을 꿈꾸기는 참 어려운 것 같습니다.
그래서인지 `흘러가는 대로 즐기자.`라는 표현이 너무 와닿네요.
_"원하는대로 되지 않아도 뭐 어때~" "잘했어~" "그거야~"_ 라고 이야기해주는 것 같았어요!

이 마지막 챕터에서 윤슬이란 단어와, 한강의 사진이 큰 교훈을 주는 것 같네요.
흘러가는 대로 두어도 그 자체로 의미있는 것이고, 때로는 반짝일 수 있다.

2024-06-11 06:57 UTC, greetings1012 requested changes
각 챕터만의 개성이 살아 있으면서도 하나의 주제로 조화롭게 어우러지는 느낌을 받았어요.
덕분에 글을 처음부터 끝까지 막힘없이 읽을 수 있었어요.
피드백 몇 개 남겼는데, 조그마한 것들이니 부담 없이 확인하셔도 돼요!
레벨 2 정말 수고하셨고, 행복한 방학 보내시길 바라겠습니다 😁

2024-06-11 06:57 UTC, greetings1012 commented on Lv2.md
> +이때 나는 Level 1의 유연성 목표를 잊지 않고 다시 떠올렸다. 의기소침에서 그치지 않고, 마라톤을 뛰듯 다른 크루들의 페이스에 휘 말리지 않으려 노력했다.
여기에 오타가 있어요! 🙋
```suggestion
이때 나는 Level 1의 유연성 목표를 잊지 않고 다시 떠올렸다. 의기소침에서 그치지 않고, 마라톤을 뛰듯 다른 크루들의 페이스에 휘말리지 않으려 노력했다. 
```

2024-06-11 06:57 UTC, greetings1012 commented on Lv2.md
> +마감이 다가올수록 증가하는 PR 수를 보며 마음은 조급해졌다. 미션을 빨리 제출해 리뷰어와 티키타카를 많이 하고 싶은데, 시간이 오래 걸리니 마음이 답답했다.
'마음은' 보다는 '마음이' 가 조금 더 자연스럽지 않을까 하는 생각이 들었어요 🥲
```suggestion
마감이 다가올수록 증가하는 PR 수를 보며 마음이 조급해졌다. 미션을 빨리 제출해 리뷰어와 티키타카를 많이 하고 싶은데, 시간이 오래 걸리니 마음이 답답했다. 
```

2024-06-11 06:57 UTC, greetings1012 commented on Lv2.md
> +> ‘나는 개발을 해도 되는 사람인가? 오래 걸리는 만큼 코드에 대한 고민이 많아졌다는 걸까? 아니면 그냥 개발에 소질이 없는 걸까???’
제가 레벨 2 내내 하고 있던 고민을 해나도 하셨군요 😢
확실히 무언가에 몰려 쉴틈없이 집중하면 자신을 돌아볼 시간이 없어 부정적인 생각이 많아지는 것 같아요.
쉼표를 찍어 자신을 돌아보는 과정을 통해 고민에서 벗어나다니, 완벽한 고민 해결 방법이었습니다 👏

2024-06-11 06:57 UTC, greetings1012 commented on Lv2.md
> +잠깐의 침묵이 곡의 흐름을 더욱 돋보이게 하고, 아름답게 만들어준다.
해나의 경험을 음악에 빗댄 표현이 좋아요!

2024-06-11 07:26 UTC, lurgi approved these changes

2024-06-11 10:38 UTC, masonkimseoul approved these changes
안녕하세요 해나! 메이슨입니다.

글 잘 읽었습니다. 빠르게 지나가는 Level 2 일정 속에서 테코톡도 완료하셨다니... 너무 멋있습니다.
저는 미션을 할 때면 생각이 많아져서 곧잘 늦게 제출하는 편인데요, 그러다보니 최근에는 밤 샐 일도 두루 있었습니다.
그러다가 이번 마지막 미션에서는 몸도 마음도 지쳐버려서 지난 주말동안 아무것도 안하고 푹 쉬었어요. 덕분에 미션 마감일인 월요일에 조금 고생했지만... 재충전할 수 있는 기회가 된 것 같습니다.

Level 3은 지금보다 더 바쁘다고 하던데, 이번 레벨에서 배운 교훈으로 더 멀리 갈 수 있었으면 좋겠습니다.
좋은 글 감사합니다! 화이팅~!

2024-06-11 13:05 UTC, Hogu59 approved these changes
해나 안녕하세요!
악어입니다 🐊 

이렇게 리뷰로 만나다니 무언가 감회가 새롭군요. 많은 글을 보면서 레벨2 역시, 크루들이 하는 고민은 한가지로 많이 귀결되는 것 같아요. 휴식을 적절한 시기에 잘 챙기는 것, 나 자신을 내 생각보다 더 돌볼만한 존재로 여기는 것, 레벨3에서는 더 바쁘겠지만 그럼에도 스스로를 더 잘 돌보며 힘내서 완주하는 해나가 되길 기대하겠습니다!

마지막까지 파이팅입니다! 😄

2024-06-11 13:05 UTC, Hogu59 commented on Lv2.md
> +<img width="583" alt="image" src="https://github.com/hxeyexn/woowa-writing/assets/103019852/c1fcc1b5-d937-48a2-abd0-faac2a82555d">
마지막 글과 사진의 조화가 아주 좋은 것 같습니다. 저는 사진자료를 사용하는걸 좋아합니다. 적절한 사진이라는 전제하에 독자를 매우 편안하게 만들어주거든요. 👍

2024-06-11 13:05 UTC, Hogu59 commented on Lv2.md
> +> ‘나는 개발을 해도 되는 사람인가? 오래 걸리는 만큼 코드에 대한 고민이 많아졌다는 걸까? 아니면 그냥 개발에 소질이 없는 걸까???’
"안 되겠다. 나 개발자 안 되겠다." 라는 말을 저도 농담으로 많이 던졌던 기억이 나네요. 근데, 꼭 개발자가 되는것만이 우리의 종착점이나 삶의 최종목표가 되어야만 하는건 아니라고 생각해요. 이런 경험을 통해 어떤 하나의 인사이트를 늘려갔다는 것만으로도 충분한 것 아닐까 하는 생각을 해봅니다. 무엇보다 해나는 나이가 아직 어리니 많은 시간과 기회가 있습니다 👍

2024-06-12 00:22 UTC, Junyoung-WON approved these changes

2024-06-12 04:17 UTC, greetings1012 approved these changes

2024-06-12 07:22 UTC, Junyoung-WON approved these changes

2024-06-12 08:29 UTC, hxeyexn commented on Lv2.md
> +이런 상태로 미션을 진행하다 보니 머릿속은 물음표로 가득 찼다.
말씀해주신 대로 `머릿속은 물음표로 가득 찼다`라는 결과에 대한 이유가 모호하네요! 피드백 감사합니다 👍
제출에 급급해 모르는 부분을 제대로 학습하지 못하다보니 미션의 진도가 잘 나가지 않아서, 머릿속은 "내가 개발자의 길을 걸어도 될까?"와 관련된 질문들로 가득 찼습니다..!

2024-06-12 09:05 UTC, hxeyexn commented on Lv2.md
> +사실 항상 나를 가만히 두지 못한 건 나 자신이었다. 그냥 가던 길을 가면 될 텐데 항상 브레이크를 내가 건다. 참 아이러니하다.
호두가 잘 이해하신 게 맞아요! 브레이크가 휴식, 쉬는 시간이라는 의미도 가진다는 걸 놓쳤네요..!
피드백 감사합니다 😊 아래처럼 수정해봤습니다!

> '나는 왜 마라톤 경주를 뛰면서 장애물을 직접 설치하고 있는 것일까? 그냥 달리기만 하면 되는 마라톤을 왜 굳이 장애물을 설치해서 힘들게 달리고 있을까?'

2024-06-12 10:58 UTC, Junyoung-WON commented on Lv2.md
> +사실 항상 나를 가만히 두지 못한 건 나 자신이었다. 그냥 가던 길을 가면 될 텐데 항상 브레이크를 내가 건다. 참 아이러니하다.
`장애물을 설치한다` 라는 표현으로 바꿔주셨네요! 표현하고자 한 의도도 명확해지면서 글이 더욱 다채로워지고 재미있어진 것 같아요!😄
제 의견 반영해주셔서 감사드립니다~☺️

2024-06-12 10:59 UTC, Junyoung-WON approved these changes

2024-07-31 02:16 UTC, merged