[레벨3 글쓰기 미션] 채드(박예찬) 미션 제출합니다.
woowacourse/woowa-writing pull request #345
Opened 2024-08-13 16:58 UTC by dpcks0509

안녕하세요 안드로이드 채드입니다!
글쓰기 리뷰 잘 부탁드립니다!
남은 레벨3도 화이팅! 🔥

[레벨3 글쓰기](https://github.com/dpcks0509/woowa-writing/blob/level2/Level3.md)

2024-08-18 07:46 UTC, le2sky requested changes
채드 안녕하세요. 아톰입니다.
채드의 감정이 잘 표현된 글 잘 읽고 가요.
작은 피드백 하나 남겼어요. 남은 레벨 3 기간도 화이팅입니다. 👍

2024-08-18 07:46 UTC, le2sky commented on Level3.md
> +팀원들 사이에서 발생할 수 있는 의견 차이, 기술적 한계, 시간 압박 등은 모두 새로운 도전 과제가 되었다.
팀원들 사이에서 기술적 한계, 시간 압박이 발생한다는게 어색하게 느껴져요. 다음과 같은 느낌은 어떨까요?

```suggestion
협업 과정에서 발생할 수 있는 팀원과의 의견 차이, 기술적 한계, 시간 압박 등은 모두 새로운 도전 과제가 되었다.
```

2024-08-18 07:46 UTC, le2sky commented on Level3.md
> +만약 내가 두려움 때문에 도전을 피했다면, 이러한 값진 경험을 얻지 못했을 것이고, 미래의 기회가 왔을 때도 여전히 두려움에 사로잡혀 도전하지 못했을 것이다.
멋있는 마인드네요. 본받고 싶습니다. 👍👍👍

2024-08-18 14:19 UTC, jinchiim requested changes
안녕하세요 채드! 글 잘 읽었습니다!
개발 속도가 굉장히 빠른 팀으로 알고 있는데 이런 이야기가 있었다니 전혀 몰랐네요!
대단하십니다!

몇가지 코멘트 남겼는데 천천히 확인해주세요! ☺️

2024-08-18 14:19 UTC, jinchiim commented on Level3.md
> +내가 지도 파트를 맡겠다고 자처한 이후, 이 부분이 얼마나 복잡하고 어려운지 금세 깨닫게 되었다.
제 프론트 지인 분들의 얼굴을 굳게 만드는 요소 중에 지도가 늘 3순위 안에 들어가있었는데,
빨리 구현하셨다는 소식을 듣고 놀랐습니다. 

처음해보셨다니 대단하시네요! 👍

2024-08-18 14:19 UTC, jinchiim commented on Level3.md
> +두려움을 극복하는 과정은 내 성장을 이끄는 중요한 요소였다.
채드가 어떻게 성장했는지 묘사하는 부분이니, 해당 문장이 사라져도 작성하신 두려움을 극복한 과정들이 성장을 이끌었다는 생각이 자연스럽게 들 것 같나는 생각이 듭니다! ☺️

2024-08-18 16:51 UTC, Todari approved these changes
안녕하세요 채드~ 토다리입니다.
저도 새로운 도전을 하는것을 정말 좋아하지만, 막상 시작하고 나서 "내가 이걸 할 수 있을까?" 와 같은 두려움을 느끼면 늘 도망가기 바쁜 것 같아요...
대신 만만한 다른 도전을 찾는 느낌...?
그렇지만 개발자로선 채드가 얘기해준 두려움을 이용하여 발전하는게 꽤나 멋있게 느껴지네요 :)
고생 많았습니다~!

2024-08-18 16:51 UTC, Todari commented on Level3.md
> +기술적으로 부족하다고 느꼈던 부분에 대해, 나는 계속해서 공부하고 연습하면서 부족한 점을 보완하려고 노력했다.
기술적으로 부족한 점이 중복되는 내용인 것 같아요!
```suggestion
나는 계속해서 공부하고 연습하면서 기술적으로 부족하다고 느꼈던 부분을 보완하려고 노력했다.
```
```suggestion
기술적으로 부족하다고 느꼈던 부분에 대해, 나는 계속해서 공부하고 연습하며 보완하려고 노력했다.
```
생각나는 방법들을 적어놓겠습니다~!

2024-08-18 16:51 UTC, Todari commented on Level3.md
> +두려움을 극복하는 과정에서 우리는 더 성장하고 나 자신을 계속해서 발전시킬 수 있는 기회를 가지게 된다.
`우리는` 과 `나 자신을` 이 함께 있으니 어색한 느낌이 있어요!
```suggestion
두려움을 극복하는 과정에서 우리는 더 성장하고 스스로를 계속해서 발전시킬 기회를 가지게 된다.
```
와 같이 고쳐도 좋을 것 같아요~!

2024-08-19 03:18 UTC, jinuemong approved these changes
안녕하세요 채드 안드로이드 누누입니다 !!!
프로젝트를 진행하면서 많은 고민을 한 흔적이 느껴지네요..
예비군 잘 보내시고 이번주도 화이팅입니다 !!

2024-08-19 09:59 UTC, jinchiim approved these changes

2024-08-19 10:04 UTC, le2sky approved these changes
고생 많으셨어요!!

2024-08-19 10:10 UTC, mzeong approved these changes
안녕하세요 채드! BE 제리입니다 👋

두려움을 원동력으로 삼은 채드의 긍정적인 마음가짐이 글에 잘 드러납니다
채드에게 레벨 3가 좋은 성장의 시간이 되었을 것 같네요 👍

좋은 글 잘 읽었습니다! 얼마 남지 않은 레벨 3 끝까지 파이팅하시길 바랍니다 💪

2024-11-18 06:15 UTC, merged