[레벨3 글쓰기 미션] 토다리(이태훈) 미션 제출합니다.
woowacourse/woowa-writing pull request #349
Opened 2024-08-13 20:07 UTC by Todari

안녕하세요 :)
6기 FE 토다리입니다 🚀 

level3 프로젝트를 진행하는 과정에서
협업을 잘 하기위한 유연성강화 경험에 대해 작성해봤어요

글쓰기 리뷰 잘 부탁드리고,
프로젝트 다들 화이팅하세요~!

2024-08-16 07:46 UTC, jinchiim requested changes
안녕하세요 토다리! 
깔끔해서 첫문장에 대한 내용만 의견 드려보았어요!

글 잘 읽었습니다!

> 곱창을 다 먹고 볶음밥으로 마무리하지 않아도 되고,
솔직히 이건 아니라고 보긴 합니다만 참겠습니다.

2024-08-16 07:46 UTC, jinchiim commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
첫문장이 개인적으로 길다고 생각합니다! 

주니어가 만족시킬 수 없는 요구사항들을 표현하기 위해서 작성하신 것 같은데, 해당하는 문장이 뒤쪽에 있다보니
두세번 정도 읽어야 표현하시려던 부분을 알겠더라고요!

혹은 글 속의 토다리가 공고를 읽는 것처럼

> 애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자> 와 협업하여 복잡한 문제를 해결한 경험.

작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다.

이렇게 시작하는 건 어떨까요?? ☺️

2024-08-16 07:46 UTC, jinchiim commented on level3.md
> +우리는 살아가면서 '더 나은 것'을 선택하는 과정을 끊임없이 마주한다. 예를 들어, '너무 재밌어 보이는 썸네일의 영상을 10분 동안 보고 자는 것과 지금 당장 잠에 드는 것 중 어느 것이 더 나은가?', '곱창으로 배를 어느 정도 채웠으니, 장소를 옮기는 것과 볶음밥으로 마무리하는 것 중 어느 것이 더 나은가?' 등의 고민을 하게 된다. 이러한 선택의
곱창을 먹었는데 볶음밥을 안먹는건 용서할 수 없네요

2024-08-16 07:46 UTC, jinchiim commented on level3.md
> +이러한 경험들 덕분에 나는 자연스레 선택과 그 근거에 대해 확신을 가지고 자신 있게 이야기할 수 있는 사람이 되었다. 그러나 레벨2의 페어프로그래밍 미션을 네 명의 다른 사람들과 네 번 진행하면서 많은 선택의 과정을 겪었고, 그 과정에서 나의 의견과 근거가 더 낫다는 확증편향에 자주 빠져 있음을 깨달았다. 그러던 중 리뷰어에게 "이 상태는 전역으로 관리하
우테코에 들어와 `정답이 없음` 을 어려워하는 크루들을 다수 보았어서 그런지 공감이 가네요! 🤔

2024-08-18 07:29 UTC, le2sky approved these changes
토다리 안녕하세요. 아톰입니다.
써주신 글 재밌게 읽고 가요. 👍👍👍👍
남은 레벨 3 기간도 화이팅입니다!

2024-08-18 07:29 UTC, le2sky commented on level3.md
> +예를 들어, 대학생 시절 다리의 임계하중을 계산할 때는 재료의 탄성계수가 낮다고 가정하기보다는 높다고 가정하여 계산하는 것이 효율적이며 정확한 값을 도출할 수 있다는 명확한 근거가 있었다. 기획자로서 서비스의 핵심 성과 지표를 근거로 선택을 하고, 작곡가로서 트렌드와 대중성을 근거로 옳다고 생각하는 선택을 해왔던 것도 마찬가지였다. 교수님, 대표님, 동료
[선택적으로 반영해주세요.]

이 부분을 읽으면서 다양한 토다리의 정보(기획자, 대학생, 작곡가)를 알 수 있었어요. 
다만, 너무 다양한 정보가 빠르게 주어지니 몰입을 방해한다고 느껴졌어요.

글 초입부에 기획자였던것을 이야기했어요. 그리고, 해당 예시에서 토다리가 강조하고 싶은 부분은 `정답에 가까운 근거있는 선택을 하려고 노력했다.` 일 것 같아요. 기획자로서 정답에 가까운 근거있는 선택을 했던 경험만을 컴팩트하게 이야기해주면 더욱 명료할 것 같다고 생각했습니다.

이 부분은 개인차가 있을 수 있는 부분이라고 생각해요. 편하게 반영 여부 결정해주시면 좋을 것 같아요.

2024-08-18 07:29 UTC, le2sky commented on level3.md
> +곱창을 다 먹고 볶음밥으로 마무리하지 않아도 되고, 재미있어 보이는 썸네일의 영상을 10분 동안 보고 잠들어도 큰 문제가 생기지 않는다. 동영상을 2배속으로 5분 만에 보고 자는 방법도 있을 것이다. 결국, 개발자에게 요구되는 '협업 경험'이란 정답이 없는 선택지에서 모두가 동의하는 선택을 이끌어내거나, 더 나은 새로운 선택지를 만들어 나가는 과정을 의미
👍👍👍

2024-08-18 17:02 UTC, dpcks0509 approved these changes
토다리, 글 잘 읽었어요!! 글 작성하시느라 수고하셨습니다!!
제가 월요일에 예비군을 가야해서 미리 Approve 해놓겠습니다!!
남은 레벨3도 화이팅입니다!!

2024-08-18 17:02 UTC, dpcks0509 commented on level3.md
> +회의 중 내 주장과 반대되는 의견이 나올 때마다 "만약 내가 이 의견을 제안했다면?"이라는 관점에서 근거를 고민해 보았다. 그 결과, 상대방의 의견을 더 자세히 듣게 되었고, 다른 의견을 쉽게 수용할 수 있었다. 양쪽의 근거 모두를 스스로 도출해냈기 때문에, '정답'이 없는 상황이라는 것을 실감하게 되었다.
나와 다른 의견을 무시하지 않고, 다른 사람의 의견을 내가 낸 것이라고 이입해서 근거를 생각해보는 방법 정말 좋은 것 같아요!

2024-08-19 03:14 UTC, jinuemong approved these changes
안녕하세요 토다리 안드로이드 누누입니다 !!
정답은 없다는 내용의 글이 저의 마인드와 비슷해서 재밌게 읽었습니다.
이번주도 화이팅해봐요 !!

2024-08-19 03:14 UTC, jinuemong commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
엄청나네요

2024-08-19 03:14 UTC, jinuemong commented on level3.md
> +물론, 이 목표를 세운다고 해서 태도가 갑자기 바뀌지는 않았다. 나와 다른 주장과 근거를 듣다 보면 상대방의 말이 끝나기도 전에 반박할 내용이 먼저 떠올랐다. 계속되는 상대방의 주장에 집중하지 못하고, 어떻게 논리적으로 설득할지에만 몰두하는 나의 모습을 발견할 수 있었다. 그 과정에서 나와 다른 의견을 수용하는 것이 얼마나 힘든 일인지 깨닫게 되었다. 하
공감이 가는 부분이네요.
의견을 좁히는 것도, 나머지 7명이 설득할 만한 의견을 내는 것도 어려웠던 것 같아요

2024-08-19 05:26 UTC, mzeong approved these changes
안녕하세요 토다리! BE 제리입니다 👋

협업을 잘 하기 위한 유강스 목표로 아주 적절한 목표를 세우신 것 같아요! 
적극적인 실험을 통해 유의미한 변화도 경험했다니 토다리가 레벨 3를 알차게 보냈음이 느껴지네요 

좋은 글 잘 읽었습니다! 마지막까지 파이팅해보아요! 💪

2024-08-19 11:50 UTC, Todari commented on level3.md
> +우리는 살아가면서 '더 나은 것'을 선택하는 과정을 끊임없이 마주한다. 예를 들어, '너무 재밌어 보이는 썸네일의 영상을 10분 동안 보고 자는 것과 지금 당장 잠에 드는 것 중 어느 것이 더 나은가?', '곱창으로 배를 어느 정도 채웠으니, 장소를 옮기는 것과 볶음밥으로 마무리하는 것 중 어느 것이 더 나은가?' 등의 고민을 하게 된다. 이러한 선택의
그럴수도 있죠

2024-08-19 12:01 UTC, Todari commented on level3.md
> +예를 들어, 대학생 시절 다리의 임계하중을 계산할 때는 재료의 탄성계수가 낮다고 가정하기보다는 높다고 가정하여 계산하는 것이 효율적이며 정확한 값을 도출할 수 있다는 명확한 근거가 있었다. 기획자로서 서비스의 핵심 성과 지표를 근거로 선택을 하고, 작곡가로서 트렌드와 대중성을 근거로 옳다고 생각하는 선택을 해왔던 것도 마찬가지였다. 교수님, 대표님, 동료
좋은 방법인 것 같아요!
아톰이 얘기했던 것 처럼 `정답에 가까운 근거있는 선택을 하려고 노력했다.`인건 맞지만, 좀 더 다양한 곳에서 지나칠 정도로 늘 정답을 선택하려 했다는걸 전달해 주고 싶어서
빠른 호흡으로 많은 경험을 작성해 넣은 의도도 있었습니다!

좋은 의견 감사해요 🚀🚀🚀

2024-08-19 12:03 UTC, Todari commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
앞부분에 개발자 공고를 한번이라도 본 독자들이 많이 공감할 수 있는 문장들을 일부러 앞에 배치해서 호기심을 불러들이는건 어떨까? 싶은 의도였어요

읽기에 많이 힘든가요????

2024-08-19 12:04 UTC, Todari commented on level3.md
> +물론, 이 목표를 세운다고 해서 태도가 갑자기 바뀌지는 않았다. 나와 다른 주장과 근거를 듣다 보면 상대방의 말이 끝나기도 전에 반박할 내용이 먼저 떠올랐다. 계속되는 상대방의 주장에 집중하지 못하고, 어떻게 논리적으로 설득할지에만 몰두하는 나의 모습을 발견할 수 있었다. 그 과정에서 나와 다른 의견을 수용하는 것이 얼마나 힘든 일인지 깨닫게 되었다. 하
정말 레벨3 프로젝트에선 의견을 얼라인하는게 제일 어렵고, 제일 많은 시간과 에너지가 소요되는 것 같아요 ㅜㅜ

2024-08-19 12:05 UTC, jinchiim approved these changes

2024-08-19 12:05 UTC, jinchiim commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
괜찮습니다! 👍

2024-08-19 12:08 UTC, Todari commented on level3.md
> +예를 들어, 대학생 시절 다리의 임계하중을 계산할 때는 재료의 탄성계수가 낮다고 가정하기보다는 높다고 가정하여 계산하는 것이 효율적이며 정확한 값을 도출할 수 있다는 명확한 근거가 있었다. 기획자로서 서비스의 핵심 성과 지표를 근거로 선택을 하고, 작곡가로서 트렌드와 대중성을 근거로 옳다고 생각하는 선택을 해왔던 것도 마찬가지였다. 교수님, 대표님, 동료
[fe07182](https://github.com/woowacourse/woowa-writing/pull/349/commits/fe071824ae9c4acae626af0494479cd34b787d9c)

앞부분에 문장을 추가해서 강조해주면 어떨까 싶어서 수정해봤습니다~!

2024-08-19 12:08 UTC, Todari commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
아뇨... 안괜찮을 것 같아서 반영했습니다 ^__^

[fe07182](https://github.com/woowacourse/woowa-writing/pull/349/commits/fe071824ae9c4acae626af0494479cd34b787d9c)

2024-08-20 04:23 UTC, jinchiim commented on level3.md
> +애자일 혹은 스크럼 환경에서의 협업 경험, JIRA, Confluence, Zeplin 등 협업 툴 사용 경험, 기획자, 디자이너 등 다양한 이해관계자와 협업하여 복잡한 문제를 해결한 경험. 작년 여름, 더 나은 환경에서 기획자로서의 커리어를 이어 나가기 위해 이직 준비를 하던 때였다. 주니어가 만족시킬 수 없는 요구사항을 나열해 놓은 주니어 기획자 채용
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋습니다^^

2024-11-18 06:15 UTC, merged