제출
woowacourse/woowa-writing pull request #407
Opened 2024-08-14 12:44 UTC by le2sky

2024-08-17 13:50 UTC, 3Juhwan approved these changes
안녕하세요. 망쵸에요 😀 

저는 아직도 플레이리스트가 없어요. 귀찮아서 유튜브 뮤직에 누가 만들어둔 플레이리스트를 들어요. 
경기패스는 지난달에서야 만들었어요. 

저는 귀찮아서 안하다가, 불편함 수치가 절정을 찍을 때 행동으로 옮기는데요. 
실행하기 전까지는 언젠가 해야 한다는 생각에 인지 비용이 낭비돼요. 
불편함을 극복하고 실행하면, 이렇게 '쉽게 해결되는데 왜 안 했을까'하는 후회하곤 해요. 
그럼에도 아직 미룬 일이 있어요. 

아톰 글을 읽고 **미루지 않기** 라는 유강스 목표 생겼어요. 감사합니다.

2024-08-18 14:25 UTC, jinchiim requested changes
안녕하세요 아톰! 글 잘 읽었습니다!
개인적으로는 유연성 강화는 의식하는 것 만으로 충분한 힘이 된다고 느껴요. 
앞으로 남은 기간들도 있으니 꾸준히 의식하면 될 듯 합니다. 👍

몇가지 소소만 코멘트 남겼으니 천천히 확인해주세요! ☺️

2024-08-18 14:25 UTC, jinchiim commented on level3.md
> +불편함에 둔한 사람이다. 몸이 아프면 적응할 때까지 이 악물고 참는다. IDE 단축키를 모르던 시절에는 손가락을 더 빠르게 움직여 적응해 버리기도 했다. 소중한 사람들이 생기면서 오래 살고 싶다는 생각은 점점 강해진다. 유감스럽게도 내가 가진 특징은 생존에 불리하다. 따라서, ‘불편함을 적응하지 않기’를 유연성 강화 스터디 목표로 정했다. 설정한 목표를
> 소중한 사람들이 생기면서 오래 살고 싶다는 생각은 점점 강해진다.

가 툭 튀어나와 글을 한번 더 읽게 되는데, 첫번째 내용과 두번째 내용을 잘 엮어볼 수 있을 것 같아요!

> 소중한 사람들이 생기면서 오래 살고 싶다는 생각은 점점 강해진다. 유감스럽게도 내가 가진 '불편함에 둔하다'는 특징은 생존에 불리하다. 몸이 아프면..

방식은 어떤가요?! ☺️

2024-08-18 14:25 UTC, jinchiim commented on level3.md
> +단시간에 드라마틱한 변화를 보여줄 비범한 인물은 아니라는 것을 안다. ‘일상을 유심히 관찰하여 사소한 불편을 해소하기’라는 작은 계획으로 시작했다. 하루는 노래를 들으면서 루터회관에 등교하고 있었다. 이때 나는 원하는 노래를 듣고 싶을 때마다 검색해서 듣고 있었다. 플레이리스트 기능을 사용하면 더욱 편하겠다는 생각을 메모장에 적었고 시간이 여유로울 때 플
어우 저는 좀 정신 없는 성격이라 하루에 몇번씩이고 노래 취향이 바뀌는 사람인데,
아톰의 노래 취향은 한결 같았나 보군요 👍

2024-08-18 14:25 UTC, jinchiim commented on level3.md
> +경기패스는 경기도 주민을 대상으로 교통비를 환급해 주는 이벤트이다. 경기패스를 신청하면 돈으로부터 발생하는 불편을 해소할 수 있다고 생각했다. 유연성 강화 스터디 시간에 이번 주까지 경기패스를 신청하지 않으면 손에 장을 지진다고 데벨업 크루들에게 선언했다. 호기롭게 선언한 것과 달리 신청 페이지에 들어가지도 않았다. 작은 경험들이 모여 임팩트를 만든다고
이제 장을 지져주시나요?

2024-08-18 17:08 UTC, Todari approved these changes
안녕하세요 아톰~ 늘 보던 토다리입니다 😃😃😃 

`불편함에 적응하지 않기`... 굉장히 어려운 유연성 강화 목표라고 생각해요
저도 comment를 단 것 처럼, 불편해도 그 불편함을 개선하는 과정이 더 불편하다고 느끼거든요...
그래도 아톰이 느끼는 불편함을 그나마 작고, 간단한데에서 부터 찾아서 노력하고 있는게 느껴지는 글이네요

고생 많았어요 :)

2024-08-18 17:08 UTC, Todari commented on level3.md
> +경기패스는 경기도 주민을 대상으로 교통비를 환급해 주는 이벤트이다. 경기패스를 신청하면 돈으로부터 발생하는 불편을 해소할 수 있다고 생각했다. 유연성 강화 스터디 시간에 이번 주까지 경기패스를 신청하지 않으면 손에 장을 지진다고 데벨업 크루들에게 선언했다. 호기롭게 선언한 것과 달리 신청 페이지에 들어가지도 않았다. 작은 경험들이 모여 임팩트를 만든다고
진짜.. 저는 K패스 신청하려고 마음먹는데 2달 걸리고, 카드 받고 나서도 회원가입해야하는거 몰라서 3달을 환급 못받았네요 ㅎㅎㅎㅎ

2024-08-18 17:11 UTC, dpcks0509 approved these changes
아톰, 글 잘 읽었어요!! 글 작성하시느라 수고하셨습니다!!
제가 월요일에 예비군을 가야해서 미리 Approve 해놓겠습니다!!
남은 레벨3도 화이팅입니다!!

2024-08-18 17:11 UTC, dpcks0509 commented on level3.md
> +단시간에 드라마틱한 변화를 보여줄 비범한 인물은 아니라는 것을 안다. ‘일상을 유심히 관찰하여 사소한 불편을 해소하기’라는 작은 계획으로 시작했다. 하루는 노래를 들으면서 루터회관에 등교하고 있었다. 이때 나는 원하는 노래를 듣고 싶을 때마다 검색해서 듣고 있었다. 플레이리스트 기능을 사용하면 더욱 편하겠다는 생각을 메모장에 적었고 시간이 여유로울 때 플
조금조금씩 변하는 모습도 충분히 멋있습니다!!

2024-08-18 17:11 UTC, dpcks0509 commented on level3.md
> +경기패스는 경기도 주민을 대상으로 교통비를 환급해 주는 이벤트이다. 경기패스를 신청하면 돈으로부터 발생하는 불편을 해소할 수 있다고 생각했다. 유연성 강화 스터디 시간에 이번 주까지 경기패스를 신청하지 않으면 손에 장을 지진다고 데벨업 크루들에게 선언했다. 호기롭게 선언한 것과 달리 신청 페이지에 들어가지도 않았다. 작은 경험들이 모여 임팩트를 만든다고
저도 기후동행카드를 산다고 선언한지 3달이 넘어서야 샀던 경험이 있어서 공감가며 읽었습니다!

2024-08-18 17:11 UTC, dpcks0509 commented on level3.md
> +다행히 스스로 개선하고자 하는 의지는 있었다. 왜 실험계획을 계속 실천하지 못했는지 고민했다. 프로젝트, 개인 공부, 인간관계에서 발생하는 인지 비용들이 많아지니 유연성 강화 목표를 의식하기 어려웠다고 판단했다. 인지 비용을 낮추기 위해 평소보다 메모장에 빈번히 들어가서 정리하는 노력을 시도했다. 노력이 효과가 있었는지는 모르겠지만 유연성 강화 스터디 목
자신의 단점을 개선하려고 하는 의지가 느껴져서 좋았어요! 앞으로 더욱 발전할 모습을 기대하겠습니다!!

2024-08-19 02:48 UTC, jinuemong approved these changes
안녕하세요 아톰 안드로이드 누누입니다 !
글이 길지 않지만 전달하려는 내용이 잘 전달되어서 좋았어요!
유연성 강화 목표를 세우고 하나씩 실천했던 경험이 인상적이네요.. 이번주도 화이팅입니다 !!

2024-08-19 02:48 UTC, jinuemong commented on level3.md
> +단시간에 드라마틱한 변화를 보여줄 비범한 인물은 아니라는 것을 안다. ‘일상을 유심히 관찰하여 사소한 불편을 해소하기’라는 작은 계획으로 시작했다. 하루는 노래를 들으면서 루터회관에 등교하고 있었다. 이때 나는 원하는 노래를 듣고 싶을 때마다 검색해서 듣고 있었다. 플레이리스트 기능을 사용하면 더욱 편하겠다는 생각을 메모장에 적었고 시간이 여유로울 때 플
저도 플레이리스트 만들기 귀찮아서 매번 검색해서 들어요🫠

2024-08-19 02:48 UTC, jinuemong commented on level3.md
> +경기패스는 경기도 주민을 대상으로 교통비를 환급해 주는 이벤트이다. 경기패스를 신청하면 돈으로부터 발생하는 불편을 해소할 수 있다고 생각했다. 유연성 강화 스터디 시간에 이번 주까지 경기패스를 신청하지 않으면 손에 장을 지진다고 데벨업 크루들에게 선언했다. 호기롭게 선언한 것과 달리 신청 페이지에 들어가지도 않았다. 작은 경험들이 모여 임팩트를 만든다고
헉 저도 해야겠네요 
감사합니다 !!

2024-08-19 02:48 UTC, jinuemong commented on level3.md
> +다행히 스스로 개선하고자 하는 의지는 있었다. 왜 실험계획을 계속 실천하지 못했는지 고민했다. 프로젝트, 개인 공부, 인간관계에서 발생하는 인지 비용들이 많아지니 유연성 강화 목표를 의식하기 어려웠다고 판단했다. 인지 비용을 낮추기 위해 평소보다 메모장에 빈번히 들어가서 정리하는 노력을 시도했다. 노력이 효과가 있었는지는 모르겠지만 유연성 강화 스터디 목
저도 메모장 자주 이용하는데 정리하는 습관이 성장에 큰 도움이 되는 것 같아요.
급하지 않게 꾸준히 노력한다면 분명 좋은 결과가 따라올 것 같습니다 !!

2024-08-19 10:19 UTC, mzeong approved these changes
안녕하세요 아톰! BE 제리입니다 👋

아톰이 목표를 이루는 과정에서 느낀 어려움과 고민이 자세히 녹아있어 글이 더 생생하게 느껴지네요 
점진적으로 나아가고자 하는 아톰의 의지가 느껴져 앞으로의 아톰이 기대됩니다 

좋은 글 잘 읽었습니다! 레벨 3 마지막까지 파이팅입니다 💪

2024-08-19 12:05 UTC, jinchiim approved these changes

2024-11-18 06:16 UTC, merged