[레벨 1 글쓰기 미션] 뽀로로(조경찬) 미션 제출합니다.
woowacourse/woowa-writing pull request #78
Opened 2024-03-28 02:35 UTC by jcoding-play

안녕하세요!! BE 뽀로로입니다~ 🐦 🤓
평소에 글을 잘 안 쓰다 보니 생각보다 너무 어렵더라구요...

부족하지만 잘 부탁드립니다~~ 👍

2024-03-30 05:29 UTC, GIVEN53 commented on Level1.md
> +그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실이 또 다른 설렘이었다.
```suggestion
그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실은 또 다른 설렘이었다.
```
지금도 읽기 좋지만 조사를 바꿔서 조금 더 자연스러운 문장이 되도록 하는 건 어떨까요?

2024-03-30 05:29 UTC, GIVEN53 commented on Level1.md
> +또한 개발과 관련된 대화에 끼기가 어려웠고, 때로는 크루들이 무슨 이야기를 하는지 이해할 수 없었다.
```suggestion
또한 개발과 관련된 대화에 끼기 어려웠고, 때로는 크루들이 무슨 이야기를 하는지 이해할 수 없었다.
```
없어도 좋을 것 같아요!

2024-03-30 05:29 UTC, GIVEN53 commented on Level1.md
> +_"학교 다닐 때 하루에 하나씩이라도 알고리즘 문제를 풀었다면 지금과 어떻게 달랐을까?"_<br>
이탤릭체를 써서 뽀로로가 어떤 생각을 했는지 더 집중해서 읽을 수 있었어요 👍🏼

2024-03-30 05:29 UTC, GIVEN53 commented on Level1.md
> +이 말을 통해 자신감을 얻었고, 다른 크루들과 나를 비교하는 것을 그만뒀다.
```suggestion
이 말에서 자신감을 얻을 수 있었고, 더 이상 다른 크루들과 나를 비교하지 않기로 했다.
```
좀 더 뽀로로의 의지를 담는 문장으로 바꿔보았어요
제안이니까 차용해도 좋고, 수정하지 않아도 좋아요!

2024-03-30 06:37 UTC, BadaHertz52 commented on Level1.md
> +우테코 크루들이 이런 생각을 하라고 한 것은 아니지만, 그들의 모습을 보며 자연스레 생각하게 되었다.
생각에 빠졌다라는 문장 뒤에 생각에 대해 나오고 뒤에 또 생각이라는 단어가 나오네요.
생각이라는 단어가 반복되어서, 마지막 문장은 생각이라는 단어보다는 그때 뽀로로의 감정이 담기면 더 좋을 것 같아요.

ex: 주눅들었다. 스스로가 작아지는 기분이였다.

2024-03-30 06:40 UTC, BadaHertz52 commented
안녕하세요. 뽀로로.
이번 글쓰기 미션을 함께하게 된 바다입니다.

저도 비공자라서 뽀로로의 글을 읽으면서 공감 많이 했어요. 
저는 아직 "제가 작아지는 기분"을 승화시시키 못하고 더 공부해야지 라는 마음만 먹었는데 이것을 뽀로로는 "노는 것"이라는 긍정적인 마인드로 승화 시키셨네요. 👏👏👏👏

수정이 이루어지면 좋을 것 같은 내용에 코멘트를 달았어요. 
뽀로로의 글쓰기에 도움이 되었으면 좋겠네요.🙂

2024-03-30 18:07 UTC, hangillee approved these changes
재밌게 잘 읽었습니다! 이미 피드백 적용하셔서 그런지 글은 아무 문제가 없는 것 같습니다.

코치와 우테코 선배들 모두 공통적으로 주는 조언이 있습니다. 우테코 크루들은 경쟁 상대가 아니라는 것입니다. 뽀로로도 다른 크루들과 비교하기를 그만두고 개발 자체를 즐기기로 결정한 것 같아 다행입니다. 앞으로도 우테코 생활 파이팅입니다!

2024-03-30 18:07 UTC, hangillee commented on Level1.md
> +질문에 대한 대답은 간단했다. 그냥 `뽀로로`라는 닉네임이 예쁘다 생각이 들었고, 다른 크루들이 나의 닉네임을 쉽게 외우고 부를 수 있도록 선택했다.
솔직히 처음 닉네임을 들었을 때 좀 당황했었습니다.. 그래도 한번 뇌리에 박힌 후로는 잊혀지질 않는 걸 보면 뽀로로의 목적은 달성한 것 같네요!

2024-04-01 17:53 UTC, reddevilmidzy requested changes
노는걸 제일 좋아하는 뽀로로의 글 잘읽었습니다!👍
뽀로로 하면 포비와의 반모가 제일 먼저 떠오르는데 인상깊게 봤었습니다
다행이 아직 남아계셨군요😂

2024-04-01 17:53 UTC, reddevilmidzy commented on Level1.md
> +그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실이 또 다른 설렘이었다.
백엔드 총인원은 80명이지만 새로운 크루라고 했을 땐 자기 자신을 뺀 79명이 맞지 않을까요👀

2024-04-01 17:53 UTC, reddevilmidzy commented on Level1.md
> +왜냐하면 나는 노는게 제일 좋은 `뽀로로`니깐
마지막 임팩트 있으면서도 귀여운데요?ㅎㅎㅎ👍

2024-04-01 17:53 UTC, reddevilmidzy commented on Level1.md
> +하지만 그들이 공통적으로 해준 말은, **우테코 미션들을 열심히 따라가다 보면 자연스레 성장한다는 것**이다.
이때 '하지만'을 사용하는게 적절한가요?👀

2024-04-01 17:53 UTC, reddevilmidzy commented on Level1.md
> +맨 위에 작성한대로 나는 노는게 제일 좋다. 그리고 이제는 노는 것이란 개발하는 것이다.
`맨 위에 작성한대로` 보다는 `앞서 말한대로` 혹은 `제목에도 적었다시피`는 어떤가요?

2024-04-01 17:53 UTC, reddevilmidzy commented on Level1.md
> +---
![image](https://github.com/woowacourse/woowa-writing/assets/78539407/2720cd6b-413b-4613-a288-4d4bbe3801dc)

샵 태그로 헤딩 주면 글 밑에 얇은 줄이 생깁니다! 그래서 추가로 --- 를 사용하지 않아도 될 거 같아요
만약 제목과 소제목을 좀 더 구분하고 싶다면 `<br>`로 줄바꿈 정도만 주어도 좋을 거 같아요

2024-04-02 04:41 UTC, llqqssttyy approved these changes
안녕하세요. 뽀로로!
글에서 뽀로로의 위트와 당찬 기운이 느껴져서 즐겁게 읽었습니다.☺️

다른 분들이 이미 좋은 리뷰를 많이 남겨 주셔서 감상을 위주로 코멘트를 달아보았습니다.
Approve를 함께 드리니 제안한 부분은 자유롭게 반영해 주세요!

2024-04-02 04:41 UTC, llqqssttyy commented on Level1.md
> +왜냐하면 나는 노는게 제일 좋은 `뽀로로`니깐
기억에 남는 마무리네요. 👍

2024-04-02 04:41 UTC, llqqssttyy commented on Level1.md
> +> "좋아하는 일을 해야지 꾸준히 할 수 있고, 결국 잘하게 된다."
정말 공감합니다..! 저도 같은 이유로 프로그래머가 되야겠다고 생각했거든요.☺️

2024-04-02 05:00 UTC, helenason reviewed
안녕하세요 뽀로로! 백엔드 6기 에버입니다.

전 전공자이지만 우테코에 잘 하는 크루들이 많아서 저도 모르게 주눅들고 위축되는 날들이 많았어요.
학교 다니면서 좀 더 열심히 살 걸.. 이러면서 후회도 많이 했답니다.
그래서 뽀로로 글에 공감 가는 부분이 많았어요! 재밌게 읽었습니다.

특히 글의 마무리가 인상깊었습니다 ㅎㅎ

노는 게 제일 좋은 뽀로로! 응원하겠습니다 😁

2024-04-02 07:18 UTC, jcoding-play commented on Level1.md
> +그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실이 또 다른 설렘이었다.
ㅎㅎ 감사합니다! 수정하였어요!! 👍

2024-04-02 07:18 UTC, jcoding-play commented on Level1.md
> +또한 개발과 관련된 대화에 끼기가 어려웠고, 때로는 크루들이 무슨 이야기를 하는지 이해할 수 없었다.
역시 프린 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +이 말을 통해 자신감을 얻었고, 다른 크루들과 나를 비교하는 것을 그만뒀다.
레벨1 글쓰기 미션 내용에서 `능동형 문장`을 쓰라는 것이 있어서 기존 방식대로 유지하도록 할게요!!
하지만 좋은 의견이라 생각합니다!! 감사해요! 😊

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +우테코 크루들이 이런 생각을 하라고 한 것은 아니지만, 그들의 모습을 보며 자연스레 생각하게 되었다.
좋은 피드백인 것 같아요! 감사합니다!! 
수정하였어요! 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +질문에 대한 대답은 간단했다. 그냥 `뽀로로`라는 닉네임이 예쁘다 생각이 들었고, 다른 크루들이 나의 닉네임을 쉽게 외우고 부를 수 있도록 선택했다.
ㅎㅎ 다행입니다ㅋㅋㅋㅋㅋ 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실이 또 다른 설렘이었다.
감사합니다!! 알려주신대로 수정하였어요!! 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +왜냐하면 나는 노는게 제일 좋은 `뽀로로`니깐
저도 맘에 드는 부분입니다ㅋㅋㅋㅋ 
감사합니다~~ㅎㅎ 🤣

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +하지만 그들이 공통적으로 해준 말은, **우테코 미션들을 열심히 따라가다 보면 자연스레 성장한다는 것**이다.
그렇네요..ㅠㅠ 놓친 부분인 것 같은데 감사해요!
수정하였습니다!! 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +맨 위에 작성한대로 나는 노는게 제일 좋다. 그리고 이제는 노는 것이란 개발하는 것이다.
수정하였습니다!! 👍 감사해요!

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +---
몰랐던 부분인데 그렇군요.. 감사합니다!!
수정하였어요! 😀

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +선배들 중에도 프리코스를 시작하며 처음 자바를 접한 분도 계셨고, 다양한 경험이 있던 분도 있었다.
사소하지 않은데요??ㅎㅎ 좋은 것 같습니다!
알려주신대로 수정하였어요! 감사합니다 👍

2024-04-02 07:19 UTC, jcoding-play commented on Level1.md
> +> "좋아하는 일을 해야지 꾸준히 할 수 있고, 결국 잘하게 된다."
같이 힘내봅시다! 🧐

2024-04-02 07:20 UTC, jcoding-play commented on Level1.md
> +설레는 마음으로 시작한 우테코 생활이 예상치 못한 감정을 가져왔다.
좋은 의견인 것 같아요!! 
하지만 기존 글이 자연스럽게 읽힌다는 느낌이 들어 유지하도록 할게요!! 👍
감사합니다!!

2024-04-02 07:20 UTC, jcoding-play commented on Level1.md
> +_"학교 다닐 때 하루에 하나씩이라도 알고리즘 문제를 풀었다면 지금과 어떻게 달랐을까?"_<br>
ㅜㅜ 같이 힘내봐요!~ 😀

2024-04-02 08:14 UTC, BadaHertz52 approved these changes
피드백 수정 사항 확인했습니다. approve 할게요. 글쓰기 미션 고생하셨습니다. 👍

2024-04-02 08:23 UTC, llqqssttyy commented
피드백 반영해주셔서 감사합니다.☺️ 레벨 1 마지막 미션 마무리 축하드려요~

2024-04-02 08:37 UTC, GIVEN53 approved these changes
놀면서 할거 다 하는 사람, 그게 뽀로로가 아닐까 생각해요 👍🏼
개발까지 즐기면서 하면 뽀로로가 얼마나 성장할지 기대가 되네요

글 재미있게 잘 읽었어요 두 달동안 뽀로로와 가깝게 지냈다보니 더 몰입해서 읽게 됐어요 ㅎㅎ
레벨1 동안 고생많았습니다! 레벨2도 화이팅 👊🏻

2024-04-02 10:38 UTC, reddevilmidzy commented on Level1.md
> +그래서 우아한테크코스에서 80명의 새로운 크루들을 만날 수 있다는 사실이 또 다른 설렘이었다.
사아실 '크루들' 이라고 표기한게 여기 한부분만은 아니여서 수정할 거면 전부다 수정하는게 맞을 거 같고, 아니다 그냥 크루들 이라고 표기할래 하신다면 전부다 크루들로 맞추시는게 좋을 거 같아요!

2024-04-02 10:41 UTC, reddevilmidzy approved these changes
`크루들` or `크루` 둘 중에 하나만 선택하여 일관성 있게 사용하면 좋을 거 같아요!

레벨 1 동안 수고 많으셨습니다!!
방항 때 푹 쉬고 레벨 2 같이 힘내보아요 💪

2024-04-03 02:00 UTC, helenason approved these changes
확인을 이제 해서 늦은 approve 죄송합니다 🥲🥲

2024-04-23 10:11 UTC, Wonmi91 commented
잘 읽었습니다 💜

2024-04-29 07:46 UTC, merged